Document that cache_page sets HTTP headers
django/django pull request #11752
Opened 2019-09-07 15:18 UTC by Flimm

Make it clearer that both `UpdateCacheMiddleware` and `cache_page` set HTTP
headers related to client-side caching. Without this, there is no documentation that `cache_page` affects the client-side cache.

2020-09-16 15:04 UTC, pope1ni requested changes

2020-09-16 15:08 UTC, pope1ni commented
@carltongibson What are your thoughts on this one?
Seems like a useful clarification given that downstream caches are not mentioned until somewhere in the bottom ~20% of the page.

2020-09-16 15:10 UTC, carltongibson commented
I'll have a 👀

2020-09-17 10:00 UTC, carltongibson approved these changes
OK, super. Thank @Flimm. Let's applied Nick's suggestions and rebased.
👍

2020-09-17 12:28 UTC, merged