Fixed #31014 -- Added FromWKB and FromWKT GIS functions.
django/django pull request #12134
Opened 2019-11-24 10:37 UTC by sir-sigurd

2020-09-16 15:38 UTC, pope1ni requested changes
@sir-sigurd Are you interested in picking this up again?

AFAICT, the only things missing are a release note and your outstanding question regarding SRIDs.

2020-09-16 15:38 UTC, pope1ni commented on tests/gis_tests/geoapp/test_functions.py
>  from django.db.models import Sum
```suggestion
from django.db import NotSupportedError, connection
from django.db.models import Sum, Value
```

2020-09-16 15:38 UTC, pope1ni commented on tests/gis_tests/geoapp/test_functions.py
> +            ),
As of 1e38f1191de21b6e96736f58df57dfb851a28c1f, `output_field` doesn't need to be defined here.

```suggestion
            functions.FromWKB(Value(g.wkb.tobytes())),
```

2020-09-16 15:38 UTC, pope1ni commented on tests/gis_tests/geoapp/test_functions.py
> +            functions.FromWKT(models.Value(g.wkt)),
```suggestion
            functions.FromWKT(Value(g.wkt)),
```

2020-09-16 15:38 UTC, pope1ni commented on docs/ref/contrib/gis/functions.txt
> +.. versionadded:: 3.1
```suggestion
.. versionadded:: 3.2
```

2020-09-16 15:38 UTC, pope1ni commented on docs/ref/contrib/gis/functions.txt
> +.. versionadded:: 3.1
```suggestion
.. versionadded:: 3.2
```

2020-09-29 10:02 UTC, felixxm commented
Closing due to inactivity.

2020-09-29 10:02 UTC, closed without merging