fold imports a bit in auth middleware
django/django pull request #12686
Opened 2020-04-08 16:19 UTC by minusf

use `auth.load_backend` consistently and use an existing import for `RemoteUserBackend`, it's used only once...

2020-11-22 16:30 UTC, minusf commented
it's just a  bit of consistency with code in other places.  i am not sure it's against any coding styles per se.

2020-11-23 10:44 UTC, pope1ni requested changes
I think that using `auth.load_backend()` is fine for consistency with all other uses, but the other change isn't worth it.

2020-11-23 10:44 UTC, pope1ni commented on django/contrib/auth/middleware.py
> +            if isinstance(stored_backend, auth.backends.RemoteUserBackend):
I'd revert this as I don't think it is better and it isn't making this more consistent with code elsewhere.
```suggestion
            if isinstance(stored_backend, RemoteUserBackend):
```

2020-11-23 10:44 UTC, pope1ni commented on django/contrib/auth/middleware.py
> +                request.session.get(auth.BACKEND_SESSION_KEY, '')
This one is fine as `auth.load_backend()` is used in `clean_username()` above.

```suggestion
                request.session.get(auth.BACKEND_SESSION_KEY, ''),
```

2021-05-19 09:33 UTC, felixxm commented
Closing due to inactivity.

2021-05-19 09:33 UTC, closed without merging