add EmalBackend CA parameters
django/django pull request #13305
Opened 2020-08-14 08:27 UTC by lsaavedr

set ssl cert and key outside a SSLContext object are deprecated and we need add CA parameters to make the server authentication

2020-10-20 14:41 UTC, mbeijen commented
I think this also would require some changes to docs/topics/email.txt

2020-11-14 10:53 UTC, felixxm commented
@lsaavedr Do you have time to keep working on this?

2020-11-14 18:54 UTC, lsaavedr commented
@felixxm yeah what do you need to fix that?

2020-11-14 19:34 UTC, felixxm commented
@lsaavedr Please check Carlton's [comment](https://code.djangoproject.com/ticket/31885#comment:1). Docs changes and tests are missing.

2020-11-14 19:51 UTC, lsaavedr commented
I'm need to learn to make test cases (I don't know how to make a test with certificates issues without a real certificate server), but I can make the documentation of the parameters added (with my bad spanglish), @carltongibson please, can you make the test cases? :'( , this issue is a security issue, a man in the middle can supplant the smtp-server identity stolen a username and password, django before send an email don't check the smtp-server identity :(

2020-11-14 23:53 UTC, lsaavedr commented
it's ok? 🥺

2020-11-24 10:39 UTC, carltongibson reviewed
Hi @Isaavedr. Thanks. It looks good. 

I've [asked on the mailing list re the additional settings here](https://groups.google.com/g/django-developers/c/UoKqsVrMxdg) — if that weren't an option, we'd probably add the `kwargs` and then use a subclass to contain setting them in `__init__()` — I just want to see what people say, since once we add a setting we do have to live with it. 

Let's see how that goes. (In any one case another setting isn't the end of the world but they grow...)

2020-11-26 10:58 UTC, carltongibson reviewed
Hi @lsaavedr — I think I was having a brain freeze this week — via the mailing list discussion, as per the `SMTP.starttls` docs, that you already linked in the ticket description 🤦 — `keyfile` and `certfile` are themselves deprecated, so as well as adding the new settings we should deprecate the old ones for removal. 

Are you OK to add that deprecation? See the [Deprecating a feature](https://docs.djangoproject.com/en/3.1/internals/contributing/writing-code/submitting-patches/#deprecating-a-feature) section of the contributing guide. 

We'd need to raise warnings if the old settings are used, and if the kwargs to `EmailBackend` are used. Then have tests checking warnings are raised. Plus `versionchanged` notes and an addition to `deprecation.txt`. — Let me know if you want/need any input on that. 

Other than that extra step, looks super. Thanks for the input! 🥇

2020-11-26 10:58 UTC, carltongibson commented on docs/topics/email.txt
> +.. class:: backends.smtp.EmailBackend(host=None, port=None, username=None, password=None, use_tls=None, fail_silently=False, use_ssl=None, timeout=None, ssl_keyfile=None, ssl_certfile=None, ssl_cafil
We need a `versionchanged` annotation to go with this.

2020-11-26 11:33 UTC, lsaavedr commented
@carltongibson Thanks for you time spend in this, but I need a little more of you attention: using keyfile and certfile is not deprecated, that is a good method of authentication (clients) and I think that this method will no deprecated in many years, or decades (pass this parameters in starttls function is deprecated in favor of using context to pass this parameters). I am add the using of CA parameters to make the server authentication, that parameters are used by the client to check the authentication of the server, is the other side of the authentication process,

thanks and regards!

2020-11-26 12:21 UTC, carltongibson commented
Hi @lsaavedr — Right, so you're (optionally) specifying a particular key to use... —  I guess worst case scenario here is we just add the settings, but it feels like we're adding too many pass-through parameters in order to expose too much of the `smtp` API... 

Does that make sense? Ideally we pick a clean default API, and then allow folks to subclass if they need to access every bell and whistle. 🤔

2020-11-26 12:53 UTC, lsaavedr commented
No, today is not optional, always the client must be check the authenticity of the server (with CA parameters), it is like (and with the same sense) the green padlock in all https websites, back in the pass two old decades was optional (client authentication and server authentication is needed).

2020-11-26 13:57 UTC, carltongibson commented
Okay... but there's a difference between using the system provided certs and loading a specific private key no? 

If you don't provide the ssl key and cert here, the server will just need to have a valid key from a CA no? (I need to have a play and test this.)

2020-11-26 14:05 UTC, carltongibson commented
Or another way of phrasing is, shouldn't the implementation we provide by default just use [create_default_context](https://docs.python.org/3.9/library/ssl.html#ssl.create_default_context) and be done with it? 
(Thanks for working with me to come the right conclusion! 🙂)

2020-11-26 14:17 UTC, lsaavedr commented
yes, you are right, from the [doc](https://docs.python.org/3/library/ssl.html#ssl.create_default_context) (purpose is SERVER_AUTH by default):

> cafile, capath, cadata represent optional CA certificates to trust for certificate verification, as in SSLContext.load_verify_locations(). If all three are None, this function can choose to trust the system’s default CA certificates instead.
> The settings are: PROTOCOL_TLS, OP_NO_SSLv2, and OP_NO_SSLv3 with high encryption cipher suites without RC4 and without unauthenticated cipher suites. Passing SERVER_AUTH as purpose sets verify_mode to CERT_REQUIRED and either loads CA certificates (when at least one of cafile, capath or cadata is given) or uses SSLContext.load_default_certs() to load default CA certificates.

with this patch it is used the system CA by default

2020-11-26 14:29 UTC, carltongibson commented
OK... so my thought is that we could deprecate the `EMAIL_SSL_` settings entirely, all except `EMAIL_USE_SSL` and just and use the system CA for the case where `EMAIL_USE_SSL = True`. 

For folks wanting specify a specific key/cert — you want to do this yes? — we could then say to subclass `EmailBackend` to provide the custom key/cert values. 

How would that seem to you? For me, we keep the normal case simple — simpler than now even — but still have the advanced case available if it's needed.

2020-11-26 14:45 UTC, lsaavedr commented
sound good for me...

2020-11-26 15:02 UTC, carltongibson commented
Yes? Super! (It covers your use-case yes?)

Are you up for adjusting the PR? 

* Make sure your case is covered, using a subclass. (Just needs the kwargs on `EmailBackend` yes?)
* Add deprecations for the existing two settings. 
* Release notes — "EmailBackend now accepts...", "... settings are deprecated", "Users needing ... should subclass EmailBackend to..." 

Seem OK to you?
Thanks. 👍

2020-11-26 18:30 UTC, lsaavedr commented
:'(

2020-11-26 19:57 UTC, carltongibson commented
Hey @lsaavedr 

I don't understand your comment. Do you not agree with the idea? Happy to discuss more (and look again in more depth next week) if you think we should do something different?

**most** people don't need to provide a specific key/cert pair no? (They can just use then system certs to determine validity of a key). 

Maybe I've missed the point. I was going from the doc and code, rather than testing against a server here, so ...

Thanks!

2021-03-02 23:43 UTC, timgraham commented on django/core/mail/backends/smtp.py
> +                'context': context
No reason to use `dict.update()` anymore.

2021-03-02 23:51 UTC, timgraham reviewed
- Add versionadded annotations to the settings in docs/ref/settings.txt
- Add the new settings to the "Core Settings Topical Index" at the bottom of docs/ref/settings.txt
- Is the "certfile must be specified" error tested? (and please add a period). I'd expecte a test with `assertRaisesMessage()`.
- I don't think the deprecation is needed as a part of this. At the very least it should likely be a separate commit, but it could probably be done as a separate ticket unless I missed the reason.

2021-03-02 23:51 UTC, timgraham commented on django/core/mail/backends/smtp.py
> +        self.ssl_keyfile = (
I would stick with the one line if/else statements. The style guide says, "Don’t limit lines of code to 79 characters if it means the code looks significantly uglier or is harder to read."

2021-03-02 23:51 UTC, timgraham commented on django/core/mail/backends/smtp.py
> +            cadata=self.ssl_cadata
Include a trailing comma in cases like this so that if more items are added later, this line doesn't have to be modified again.

2021-03-02 23:51 UTC, timgraham commented on django/core/mail/backends/smtp.py
> +
please omit the blank line

2021-03-31 07:14 UTC, carltongibson commented
OK, update: following discussion on #13728, let's push this forwards adding the settings now. 

I'll then create a new ticket to look at moving the pass-through parameters into the Email Backend (so we have 1 or 2 settings, not one for every option of the underlying protocol) 

I'll address Tim's comments now, and then we'll have a last look.

2021-03-31 08:52 UTC, carltongibson requested changes
Hi @lsaavedr — sorry for the back and forth here, but I need to ask for a change of approach. 

Previously, I was concerned about adding the extra settings which are merely pass-through parameters, and which most users never need. (As per our discussion, if `ssl_cafile` &co are `None` `create_default_context()` will just use the system CA certificates, which is what almost all users are going to want.) 

Looking again I'm still concerned about the exact same thing. It's an unwarranted increase in the API surface area. Doubting myself due to the discussion, I asked for a second opinion from @felixxm and he agreed. 

What we'd like it so add the kwargs to `EmailBackend`, have the code use an SSLContext as suggested, and then recommend in the docs that folks subclass if they need to set the parameters. 

At the same time, in a second commit we think we should deprecate `EMAIL_SSL_CERTFILE` and `EMAIL_SSL_KEYFILE`, for the same reasons. 

(There's an argument for moving **all** these settings into the backend, leaving just `BACKEND`, but with `HOST` &co, at least the majority of users need to set these.) 

I hope that makes sense. 

Previously you expressed dissatisfaction when I asked for these changes. Sorry about that. Bottom line is we're just trying to get it right, keep the quality as high as we can, and we need to remember that once a change is in we have to live with it. 

Are you though up for finishing this off? I understand if not but if so we can deassign it, and likely get it picked up by another contributor. 

Thanks for your efforts!

2021-03-31 13:49 UTC, lsaavedr commented
Hi @carltongibson using system CA to server certificates it's okay, but please be aware to not remove the optional client certificate, these are important and always good option in any email settings,

thanks!

2021-03-31 15:23 UTC, carltongibson commented
Hey @lsaavedr -- yes, we're happy to add the kwargs to EmailBackend, so if you want it, you'd just creat a subclass and set the values in init.

2021-03-31 15:24 UTC, timgraham commented
Hey Carlton, I worked on my review comments a little while ago as I was considering finishing this. I pushed them here for now. Not sure I agree with the subclass approach. I continued the [django-developers discussion](https://groups.google.com/g/django-developers/c/UoKqsVrMxdg).

2021-03-31 17:00 UTC, carltongibson commented
Thanks @timgraham. I will follow up there in the morning.

2023-02-02 10:32 UTC, felixxm commented
Fixed in 2848e5d0ce5cf3c31fe87525536093b21d570f69.

2023-02-02 10:32 UTC, closed without merging