Fixed #10929 -- Support a default value for Sum
django/django pull request #13645
Opened 2020-11-06 04:00 UTC by bartonip

Added default=None keyword argument to Sum

Added tests for each supported output_field type

Update docs/topics/db/aggregation.txt

https://code.djangoproject.com/ticket/10929

2020-11-06 05:28 UTC, felixxm reviewed
@bartonip Thanks for this patch :+1: What do you think about [Simon's proposition](https://code.djangoproject.com/ticket/10929#comment:20) to add `coalesce` instead of default?

Also, release notes and `versionchanged` annotations are missing.

2020-11-06 08:17 UTC, bartonip commented
@felixxm I think Simon's idea is great, however I think the more likely search terms to reach/search for when trying to solve this problem would be something to do with "default value" or "base value". 

I am definitely happy to include support for expressions in this patch, but I think the kwarg name should still be default.

2020-11-06 10:05 UTC, bartonip commented
Adding onto my previous comment, the pattern for a default value for fields is `default` so I think continuing this pattern would make it easier for those who are not familiar with the framework to find the documentation for this argument. Especially if you do not have too much SQL experience, you wouldn't know what `coalesce` does.

2020-11-13 10:46 UTC, bartonip commented
@felixxm The issues have been fixed.

2020-11-13 12:00 UTC, felixxm reviewed
@bartonip Thanks :+1: Please check tests that don't work on PostgreSQL and Oracle.

2020-11-13 13:46 UTC, pope1ni requested changes
I don't think this is the correct approach. If the `default` argument is not `None` we should wrap the function in `as_sql()` with `Coalesce()`. This is important for allowing expressions such as the following:

- `Sum('rating', default=F('other'))`
- `Sum('rating', default=0) + Value(5)`

Basically we want the following:

- `Sum('rating', default=None)` → `SUM(rating)`
- `Sum('rating', default=0) + Value(5)` → `COALESCE(SUM(rating), 0) + 5`

This is essentially what @charettes has been proposing on the ticket. I do, however, agree that `default` as an argument name is probably more discoverable than `coalesce` and we can document that it wraps the aggregate function with `COALESCE` to replace `None` with the specified default.

We should also do this in the `Aggregate` base class rather than for `Sum` only, as this issue also applies to `Avg`, etc. This was also mentioned in the ticket.

At the end of the day this is merely syntactic sugar for wrapping the expression with `COALESCE` which is the way it'd be handled if you were writing raw SQL, but it is worth having as if is a very common use case and something that people seem to have trouble understanding.

2020-11-13 13:46 UTC, pope1ni commented on django/db/models/aggregates.py
> +            value = value.microseconds
I don't understand why this is here? Also why not `value.total_seconds()`? Or am I missing something?

```python
>>> from datetime import timedelta
>>> delta = timedelta(microseconds=90000000123)
>>> delta
datetime.timedelta(days=1, seconds=3600, microseconds=123)
>>> delta.microseconds
123
>>> delta.total_seconds()
90000.000123
```

2021-02-19 18:14 UTC, recepsirin approved these changes

2021-02-21 01:45 UTC, pope1ni commented
Superseded by #14026.

2021-02-21 01:45 UTC, closed without merging