Fixed #21021 -- Pass Geometry instead of Unknown as geometry name in gis forms
django/django pull request #13718
Opened 2020-11-25 23:12 UTC by yagoulas

https://code.djangoproject.com/ticket/21021

BaseGeometryWidget passes "Unknown" as the default value for geom_type whereas we expect it to be "Geometry".

In OGRGeomType 'geometry' is explicitly converted to 'unknown' so I hesitated to change this class and opted to do the conversion in BaseGeometryWidget.

2020-11-26 05:07 UTC, felixxm reviewed
@yagoulas Thanks for this patch :+1: Tests are required.

2020-11-26 09:12 UTC, pope1ni reviewed
As @felixxm says, a test is required.

I think the most appropriate place would be in `tests/gis_tests/test_geoforms.py`.

2020-11-26 21:39 UTC, yagoulas commented
Hello, thanks for the swift review. I fixed the points you raised. 
I made an additional change so that geom_type is always a string instead of being either a OGRGeomType or a string.

2020-11-27 08:36 UTC, pope1ni requested changes
Hi @yagoulas 

Thanks for the updates. Just a few more tweaks and I think we're there.

2020-11-27 08:36 UTC, pope1ni commented on django/contrib/gis/forms/widgets.py
> +        geom_type = str(gdal.OGRGeomType(self.attrs['geom_type']))
Using `.name` would be better than `str()`:

```suggestion
        geom_type = gdal.OGRGeomType(self.attrs['geom_type']).name
```

2020-11-27 08:36 UTC, pope1ni commented on tests/gis_tests/test_geoforms.py
> +        # attrs argument overrides self.attrs
```suggestion
        # The Widget.get_context() attrs argument overrides self.attrs.
```

2020-11-27 08:36 UTC, pope1ni commented on tests/gis_tests/test_geoforms.py
> +        context = widget.get_context('point', None, None)
It seems odd to keep `'point'` here, even though it probably doesn't make much difference.
```suggestion
        context = widget.get_context('polygon', None, None)
```

2020-11-27 08:36 UTC, pope1ni commented on tests/gis_tests/test_geoforms.py
> +        context = widget.get_context('point', None, None)
Likewise, it seems odd to keep `'point'` here:
```suggestion
        context = widget.get_context('geometry', None, None)
```

2020-11-27 08:36 UTC, pope1ni commented on tests/gis_tests/test_geoforms.py
> +        # Geometry geom_type gets transfered properly in the returned context
```suggestion
        # Widget.get_context() returns 'Geometry' instead of 'Unknown'.
```

2020-11-27 08:36 UTC, pope1ni commented on tests/gis_tests/test_geoforms.py
> +        # geom_type gets transfered in the returned context
```suggestion
        # Widget.get_context() returns expected name for geom_type.
```

2020-11-27 11:39 UTC, pope1ni approved these changes
I think this is ready to be looked at again @felixxm.

2020-11-28 08:18 UTC, felixxm approved these changes
@yagoulas Thanks :+1: Welcome aboard :boat: 

I moved extra tests to a separate commit.

2020-11-28 08:42 UTC, felixxm commented
buildbot, test on selenium.

2020-11-28 11:03 UTC, merged