Refs #32381 -- [WIP] Include number of rows matched in bulk_update() return value
django/django pull request #14125
Opened 2021-03-14 15:26 UTC by diego-lima

[Ticket #32381 -- Include number of rows matched in bulk_update() return value](https://code.djangoproject.com/ticket/32381)

- [x] Implement the simplest approach (return the sum of its updates)
- [ ] Add documentation (`bulk_update`)
- [ ] Add documentation (changelogs)
- [ ] Discuss/resolve [Tim McCurrach](https://code.djangoproject.com/ticket/32381#comment:8)'s duplicates problem
- [ ] Discuss/resolve [Chris Jerdonek](https://code.djangoproject.com/ticket/32381#comment:1)'s future-proofing proposal

2021-03-14 21:41 UTC, pope1ni requested changes
Please update the [`.bulk_update()` documentation](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#bulk-update) to mention that a count of updated ~~rows~~ objects is returned, show the returned value in the example, and also add a `versionchanged` annotation.

I think this is also worth mentioning in the release notes for 4.0 as it is a change to a public method.

I've flagged this as *needs documentation* in ticket-32381.

While there is some preliminary discussion about a "future-proofed" return value, I think that it makes sense to go ahead with this returning the sum. It seems sensible that `.bulk_update()` mirrors `.update()` and any potential change to the latter, if it occurs, should be implemented in the same way in the former. In short, I agree with Simon's [comment](https://code.djangoproject.com/ticket/32381#comment:10).

I wouldn't worry too much about the issue with duplicates. We can just ensure there is an appropriate caveat in the documentation. If anything we'd expect the returned count of ~~rows~~ objects updated to match the number of objects passed to `.bulk_update()`, but we may end up with less if there are duplicates in the same batch. This is different to the count returned by `.update()` as, in that case, we don't know how many objects we're going to be attempting to update beforehand.

2021-03-14 21:41 UTC, pope1ni commented on django/db/models/query.py
> +            rows = 0
I'd move this above the `with transaction.atomic(...):` line above.

2021-03-14 21:41 UTC, pope1ni commented on tests/queries/test_bulk_update.py
> +
I don't think we need this new test and should update existing tests instead.

For example, you could check that `0` is returned in `test_empty_objects()` and that `2000` is returned in `test_large_batch()`. I imagine these would be sufficient.

2021-03-15 00:57 UTC, diego-lima commented
Oops! I might need help with this failing JavaScript test. Right now I have no clue what went wrong :(

2021-03-15 07:27 UTC, pope1ni commented
> Oops! I might need help with this failing JavaScript check. Right now I have no clue what went wrong :(

Don't worry, it's unrelated.

2021-03-15 12:35 UTC, tim-mccurrach reviewed
I'm not convinced in the case of `bulk_update` that a return value actually adds any value. 

 - The reason the return value is useful for `update` is that we are acting on a queryset, not a list. The return value saves us doing an additional `count` call. This is not the case for `bulk_update` though. The simplest way to know how many objects we're dealing with is just `len`. If the return value consistently told us the number of rows (not objects) that are affected, that might add value. But because of the duplicates/batches issue, it won't do that consistently, and could return any number between `len(objs)` and the number of rows.
 
 - The bigger issue with `bulk_update` is that, in the case of duplicates, only the first object (per batch) will result in an update. The most important thing you want to happen is that your data is updated correctly, and I imagine that in most cases this is not the desired behaviour. With this in mind, if you are using `bulk_update` correctly, you probably don't have any (or will have removed) any duplicates. My point here is: The duplicates issue is an edge case, and the majority of the time `len` would do just fine.

2021-03-23 06:31 UTC, felixxm commented on django/db/models/query.py
> +        return rows
> but if that's what we are choosing to do, we may as well just return len(objs).

I disagree, we shouldn't use `len(objs)`. First of all `update()` returns the number of matched rows, so there is no need to use a custom logic here. Secondly, `len(objs)` may not be equal to the total number of rows from `update()` due to race-conditions

2021-03-23 06:41 UTC, felixxm commented on tests/queries/test_bulk_update.py
> +        self.assertEqual(count, 2000)
We should add an extra tests for duplicates, e.g. `bulk_update()` with the same object twice.

2021-03-23 18:46 UTC, tim-mccurrach commented on django/db/models/query.py
> +        return rows
> `len(objs)` may not be equal to the total number of rows from `update()` due to race-conditions

Good point, I didn't think of that :( Thanks for pointing this out

2021-05-05 09:49 UTC, felixxm commented
@diego-lima Do you have time to keep working on this?

2021-05-05 10:40 UTC, diego-lima commented
@felixxm I've been on a tight schedule for the past month. I'll be able to return to this in two weeks.

2021-05-05 10:41 UTC, felixxm commented
Thanks, sounds good :+1:

2021-06-23 11:07 UTC, felixxm commented
Closing due to inactivity. Feel-free to open a new PR.

2021-06-23 11:07 UTC, closed without merging

2021-06-28 08:33 UTC, felixxm commented
Superseded by #14559.