Draft PR for #31937
django/django pull request #14226
Opened 2021-04-06 14:23 UTC by uri-rodberg

https://code.djangoproject.com/ticket/31937

Just a draft PR. I'm waiting for feedback. The translations still needs to be updated in every language - also on Transifex.

2021-04-06 15:24 UTC, felixxm commented
@uri-rodberg Thanks for this patch :+1: Please revert all updates in `.po`/`.mo` files, only changes in `django/utils/timesince.py` and related tests are required.

2021-04-06 15:33 UTC, uri-rodberg commented
> @uri-rodberg Thanks for this patch 👍 Please revert all updates in `.po`/`.mo` files, only changes in `django/utils/timesince.py` and related tests are required.

@felixxm Done. Please notice that there are two Python files changed, not one.

2021-04-07 12:01 UTC, claudep requested changes
That's a good start. You'll also have to update `timesince` to pass a dict `... % {'number': count`}. Then, for the tests to path, the humanize cs django.po and .mo need to be updated as well (used in `test_inflection_for_timedelta`).

2021-04-07 12:12 UTC, uri-rodberg commented
> That's a good start. You'll also have to update `timesince` to pass a dict `... % {'number': count`}. Then, for the tests to path, the humanize cs django.po and .mo need to be updated as well (used in `test_inflection_for_timedelta`).

@claudep Can you update the code? It's about 20 lines of Python and I don't want to make any mistakes.

The original PR included hundreds of .po files but @felixxm asked me to revert them.

How are we going to handle this with Transifex?

2021-04-07 12:43 UTC, claudep commented
My version of the patch: #14233

2021-04-07 12:43 UTC, closed without merging

2025-05-29 11:47 UTC, aiswaryasankar commented
## Review Summary

Skipped posting 12 drafted comments based on your review threshold. Feel free to update them [here](https://www.entelligence.ai/pull-requests).

<details>
<summary>Draft Comments</summary>

<details>
<summary>django/contrib/humanize/templatetags/humanize.py:177-220</summary>

```
`time_strings`, `past_substrings`, and `future_substrings` dictionaries in `NaturalTimeFormatter` are defined as class attributes, which is efficient and avoids repeated allocations.
```

Scores:
- Production Impact: 1
- Fix Specificity: 1
- Urgency Impact: 1
- Total Score: 3

Reason for filtering: The comment describes an efficiency benefit, not a bug or issue, and does not suggest any fix or improvement. It has minimal production impact, no clear fix, and very low urgency.

Analysis: The comment is informational, not actionable, and does not identify a problem or suggest a change. It does not meet the threshold for inclusion.
</details>

<details>
<summary>django/contrib/humanize/templatetags/humanize.py:223-259</summary>

```
The docstring for `NaturalTimeFormatter.string_for` lacks a description of parameters and return value, reducing clarity for maintainers.
```

Scores:
- Production Impact: 1
- Fix Specificity: 5
- Urgency Impact: 1
- Total Score: 7

Reason for filtering: The comment addresses a style/documentation issue (missing docstring details) which has minimal production impact, low urgency, and while the fix is clear, the total score does not meet the inclusion threshold.

Analysis: The lack of parameter and return value documentation in the docstring does not affect production behavior or cause failures. The fix is specific and clear, but the urgency and production impact are very low, resulting in a total score below the required threshold.
</details>

<details>
<summary>django/utils/timesince.py:17-24</summary>

```
The `TIMESINCE_CHUNKS` tuple is recalculated on every import; consider using constants for improved clarity and maintainability.
```

Scores:
- Production Impact: 1
- Fix Specificity: 5
- Urgency Impact: 1
- Total Score: 7

Reason for filtering: The comment describes a maintainability improvement, not a bug with production impact. The suggested change is stylistic and does not affect runtime behavior or cause failures. The total score does not meet the inclusion threshold.

Analysis: The issue is about code clarity and maintainability, not a production bug. The fix is clear, but the impact and urgency are minimal, resulting in a low total score.
</details>

<details>
<summary>django/utils/timesince.py:63-70</summary>

```
The `timesince` function is long and can be refactored by extracting leap year adjustment logic for better readability.
```

Scores:
- Production Impact: 1
- Fix Specificity: 5
- Urgency Impact: 1
- Total Score: 7

Reason for filtering: The comment suggests a readability refactor with no significant production impact or urgency, and the fix is not critical. The total score does not meet the required threshold.

Analysis: The suggested change is a code readability refactor with minimal production impact and low urgency. While the fix is clear and specific, the overall necessity is low, resulting in a total score below the required threshold for inclusion.
</details>

<details>
<summary>django/utils/timesince.py:27-101</summary>

```
The `timesince` and `timeuntil` functions share similar logic; consider extracting shared logic to improve maintainability.
```

Scores:
- Production Impact: 1
- Fix Specificity: 4
- Urgency Impact: 2
- Total Score: 7

Reason for filtering: The comment suggests a maintainability improvement by refactoring similar logic, but it does not address a production-impacting bug. The production impact is minimal, and the urgency is low, resulting in a total score below the required threshold.

Analysis: The suggestion is clear and specific but addresses code maintainability rather than a production issue. The low production impact and urgency make this a non-critical, nice-to-have refactor, so it does not meet the inclusion threshold.
</details>

<details>
<summary>django/utils/timesince.py:1-101</summary>

```
No exploitable security vulnerabilities found; all user-facing strings are translated and not directly exposed to injection or XSS.
```

Scores:
- Production Impact: 1
- Fix Specificity: 1
- Urgency Impact: 1
- Total Score: 3

Reason for filtering: The comment does not identify any actionable issue or required fix, and the total score does not meet the inclusion threshold.

Analysis: The comment simply states that no security vulnerabilities were found, provides no fix or actionable direction, and has minimal production or urgency impact. It does not meet the threshold for inclusion.
</details>

<details>
<summary>django/utils/timesince.py:28-46</summary>

```
The docstring for `timesince` is verbose and could be more concise; excessive detail can obscure key usage information.
```

Scores:
- Production Impact: 1
- Fix Specificity: 4
- Urgency Impact: 1
- Total Score: 6

Reason for filtering: The comment addresses a style issue (docstring verbosity) with minimal or no production impact, low urgency, and the fix is not critical. The total score does not meet the inclusion threshold.

Analysis: The issue is stylistic and does not affect production. The fix is clear but not urgent or impactful, resulting in a low total score.
</details>

<details>
<summary>django/utils/timesince.py:99-100</summary>

```
The docstring for `timeuntil` is too brief and lacks parameter/return details, reducing clarity for maintainers.
```

Scores:
- Production Impact: 1
- Fix Specificity: 5
- Urgency Impact: 1
- Total Score: 7

Reason for filtering: The comment addresses a style/documentation issue with no production impact, and the total score does not meet the required threshold for inclusion.

Analysis: The issue is purely stylistic and does not affect production. The fix is clear and specific, but urgency and impact are minimal, resulting in a low total score.
</details>

<details>
<summary>django/utils/timesince.py:27-101</summary>

```
The variable name `d` in `timesince` and `timeuntil` is non-descriptive; unclear naming reduces readability.
```

Scores:
- Production Impact: 1
- Fix Specificity: 5
- Urgency Impact: 1
- Total Score: 7

Reason for filtering: The comment addresses a style issue (variable naming) with minimal production impact and low urgency. The total score does not meet the required threshold for inclusion.

Analysis: The issue is purely stylistic and does not affect production stability or functionality. The fix is clear and direct, but the urgency and impact are very low, resulting in a total score below the required threshold.
</details>

<details>
<summary>django/utils/timesince.py:27-101</summary>

```
The variable name `now` is ambiguous; consider `reference_time` for clarity and consistency.
```

Scores:
- Production Impact: 1
- Fix Specificity: 5
- Urgency Impact: 1
- Total Score: 7

Reason for filtering: The comment addresses a style issue (variable naming) with minimal production impact and low urgency, resulting in a total score below the required threshold.

Analysis: The suggestion improves code clarity but does not affect production stability or urgency. The fix is clear and specific, but the overall impact is low, so the comment should be removed under the current filtering rules.
</details>

<details>
<summary>django/utils/timesince.py:75-75</summary>

```
The comment on line 75 is redundant with the code and could be removed for conciseness.
```

Scores:
- Production Impact: 1
- Fix Specificity: 2
- Urgency Impact: 1
- Total Score: 4

Reason for filtering: The comment addresses a minor style issue with no production impact, no clear fix direction, and very low urgency. The total score does not meet the inclusion threshold.

Analysis: The review comment is about a redundant comment in code, which does not affect production, is a vague suggestion, and is not urgent. Th [...]

2025-05-29 12:05 UTC, felixxm commented
@aiswaryasankar Please stop submitting such a useless AI-generated comments or I'll be forced to block your account.