[WIP] Try moving get_from_clause() to later.
django/django pull request #14683
Opened 2021-07-22 13:33 UTC by schinckel

I have two seperate apps that add different functionality related to the ORM, that are both hitting problems because by the time the SQL for the WHERE clause is generated, the FROM clause is all done.

I wonder if anyone knows if there is a reason this is the case?

This PR is a test to see if there are any weird failures that are triggered by moving these bits around.

2023-05-09 04:30 UTC, auvipy requested changes
are you still considering to continue this? if not it would be better to close this for now and reopen later

2023-05-09 09:04 UTC, schinckel commented
@auvipy I'd completely forgotten about this.

I'll pull it down and see how it all goes.

2023-05-09 10:06 UTC, felixxm commented
@schinckel Please create a new ticket where you will summarize a discussion about moving this call. Also, some docstrings should be updated e.g. `get_from_clause()`.

2023-05-09 10:07 UTC, shangxiao commented
devil's advocate: if this exhibits behaviour change for you then it's likely to exhibit behaviour change for others… is this something that needs discussion on the ML or forum?

2023-05-09 10:09 UTC, felixxm commented
> devil's advocate: if this exhibits behaviour change for you then it's likely to exhibit behaviour change for others… is this something that needs discussion on the ML or forum?

If I remember correctly this has already been discussed on the mailing list.

2023-05-09 10:10 UTC, felixxm commented
... but [shortly](https://groups.google.com/g/django-developers/c/X2XqA_S3IRA/m/5dje0pZXBwAJ).

2023-06-21 07:52 UTC, felixxm commented
Closing per ticket-34552 due to inactivity and lack of consensus.

2023-06-21 07:52 UTC, closed without merging