fixed small english ambiguity
django/django pull request #14710
Opened 2021-07-28 21:21 UTC by Nicolas-Reyland

The ":" colon char was in both the parts, which could lead to ambiguous understanding of the text (e.g. "<int::question_id>" instead of "<int:question_id>"). I fixed that and added the descriptor of the ":" colon, since it wasn't made notice of anymore.

2021-07-29 22:52 UTC, pope1ni requested changes

2021-07-29 22:52 UTC, pope1ni commented on docs/intro/tutorial03.txt
> +will be used to identify the matched pattern, and the ``<int`` part is a
I think we can remove the angle brackets two as they're already discussed and I think it is wrong to include them.
```suggestion
view function. The ``question_id`` part of the string defines the name that
will be used to identify the matched pattern, and the ``int`` part is a
```

2021-07-29 22:52 UTC, pope1ni commented on docs/intro/tutorial03.txt
> +The ``:`` separates those parts.
```suggestion
The colon (``:``) separates the converter and pattern name.
```

2021-07-30 14:19 UTC, Nicolas-Reyland commented
I like your changes. I just applied them, if I'm not mistaken.

2021-07-30 20:52 UTC, pope1ni approved these changes
Thanks 🙂

2021-08-02 06:00 UTC, merged