Fixed #33025 - Improved performance of Query.build_lookup
django/django pull request #14769
Opened 2021-08-14 15:22 UTC by kezabelle

[Ticket is 33025](https://code.djangoproject.com/ticket/33025), spawned out of prior ticket [33015](https://code.djangoproject.com/ticket/33015).

Of the built-in backends, only Oracle treats empty strings and nulls as equal, so avoid testing the default connection backend for `interprets_empty_strings_as_nulls` if it can be established from the lookup that it wouldn't affect the lookup instance returned.
This improves performance a small amount for most lookups being built, because accessing the connections requires touching the thread critical `Local` which is an expensive operation.

2021-08-14 16:29 UTC, smithdc1 commented
Have you tried the pre-commit hooks? (I know it's another thing) it helps me fight the linter, sadly it doesn't cover spelling so I still fail regularly at that.

2021-08-16 10:08 UTC, kezabelle commented
Heya,

> Have you tried the pre-commit hooks?

In a previous life, I've used pre-commit hooks plenty. But IMHO they're an unsalvageable idea with git, where they're opt-in and their value is so easily subverted. Also IME not all git GUIs even play well with them, as they won't necessarily inherit the right `PATH` and whatever else might be necessary, depending on how they're opened. Even then, I've got little experience with `pre-commit` the package, having used `lefthook` mostly (and of _course_ their YAML config formats are different...)
That aside, I don't find the linters [flake8, isort] to be super useful, given they mostly just whine at me about stylistic indents or line length or at best unused imports. For one, I don't care about those (use `black`/`darker`), for another, if the tool isn't going to fix such simple things for me, then it's no use :)

Anyway, to the PR at hand, I _assume_ (and/or hope) that the bionic CI would pass as all the others have (there's no reason they shouldn't) but bionic seems to have been erroring all PRs for the last few days due to a `git` issue.

2021-08-17 12:26 UTC, ngnpope requested changes
Reading the comment above this bit about `is_nullable()`, I thought I'd check for other similar cases that you could tweak...

https://github.com/django/django/blob/556ea156968cecbd72860b72cdeacf7d7b384789/django/db/models/sql/query.py#L2336-L2339

Could be changed to:

```python
        return field.null or (
            field.empty_strings_allowed and
            connections[DEFAULT_DB_ALIAS].features.interprets_empty_strings_as_nulls
        )
```

(Don't forget the double-dash in your PR title and commit message, i.e. `Fixed #33025 -- ...`)

2021-08-17 12:26 UTC, ngnpope commented on django/db/models/sql/query.py
> +                connections[DEFAULT_DB_ALIAS].features.interprets_empty_strings_as_nulls):
As you're reordering here anyway, I'd reformat this to:
```suggestion
        if (
            lookup_name == 'exact' and lookup.rhs == '' and
            connections[DEFAULT_DB_ALIAS].features.interprets_empty_strings_as_nulls
        ):
```

2021-08-17 12:48 UTC, kezabelle commented
> Reading the comment above this bit about `is_nullable()`, I thought I'd check for other similar cases that you could tweak...

I have exactly that change + 4 other commits in another branch, having searched for uses of `connections[` and looked at their usages. None are substantial, but they're separate enough that I was going to do a second ticket off the back of this one to see which might be worth it :)

2021-08-19 11:29 UTC, felixxm commented
@kezabelle Thanks :+1:

2021-08-19 11:53 UTC, merged