Simplified definition of ManagementForm.
django/django pull request #15171
Opened 2021-12-09 16:44 UTC by adamchainz

This helps introspection, and it follows the comment in `BaseForm.__init__` not to avoid changing `base_fields`.

Thanks to Silvio Gutierrez and Baptiste Melon for investigating.

2021-12-09 17:01 UTC, bmispelon commented
Big fan of 🍈 but my name has a few extra letters in it 😅

2021-12-09 17:20 UTC, bmispelon requested changes
I don't know the significance of using `maxDiff = None`. A quick `git grep maxDiff` shows a lot of different values.

Also, my name is spelled "Mispelon", if you could change that in the commit message that'd be great, thanks.

Other than that the change seems ok 👍🏻

2021-12-09 17:34 UTC, adamchainz commented
> Big fan of 🍈 but my name has a few extra letters in it 😅

Sorry! 😳 Fixed in PR and commit.

> I don't know the significance of using `maxDiff = None`. A quick `git grep maxDiff` shows a lot of different values.

Ah this was only to debug the test failure. I will revert it.

https://docs.python.org/3.10/library/unittest.html#unittest.TestCase.maxDiff

2021-12-10 09:05 UTC, felixxm commented
Thanks y'all :+1:

2021-12-10 09:49 UTC, merged