Added example for optimized full text search with GinIndex
django/django pull request #15350
Opened 2022-01-23 19:03 UTC by roskakori

This is a first proposal to improve the documentation on full text search performance.

For details, see <https://code.djangoproject.com/ticket/33459#ticket>.

2022-01-23 20:13 UTC, pauloxnet requested changes

2022-01-23 20:13 UTC, pauloxnet commented on docs/ref/contrib/postgres/search.txt
> +        search_vector = models.SearchVectorField(null=True)
```suggestion
        search_vector = SearchVectorField(null=True)
```

2022-01-23 20:13 UTC, pauloxnet commented on docs/ref/contrib/postgres/search.txt
> +        # search in an efficient and enriched format.
```suggestion
```

I would remove comments in code and move in the above text.

2022-01-23 20:13 UTC, pauloxnet commented on docs/ref/contrib/postgres/search.txt
> +            # The index to search the search_vector efficiently.
```suggestion
```

I would remove comments in code and move in the above text.

2022-01-23 20:13 UTC, pauloxnet commented on docs/ref/contrib/postgres/search.txt
> +
Some imports are missings

2022-01-23 20:13 UTC, pauloxnet commented on docs/ref/contrib/postgres/search.txt
> +Only once the other other fields have been stored in the database you can
```suggestion
Only once the other fields have been stored in the database you can
```

2022-01-23 20:13 UTC, pauloxnet commented on docs/ref/contrib/postgres/search.txt
> +
Add also results as above.

2022-01-24 05:28 UTC, felixxm commented
Closing per ticket.

2022-01-24 05:28 UTC, closed without merging