Fixed #33842 -- Add links to github for file paths in the documentation
django/django pull request #15808
Opened 2022-06-30 12:46 UTC by rayman1104

ticket-33842 

It's sometimes confusing to see such statements in the [docs](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#admin-overriding-templates):

> The admin template files are located in the **contrib/admin/templates/admin** directory.

Since I don't have such path in my project, I don't know where to go to find it. Finally, I understood that the Django's source code is meant and I can find it on github. But it would be more clear if we just had a link on github there:

> The admin template files are located in the [django/contrib/admin/templates/admin](https://github.com/django/django/tree/main/django/contrib/admin/templates/admin) directory.

Here I've used a straightforward approach of just using sphinx links to fix it. But maybe there is some better approach like using semantic markup
```
:file:`django/contrib/admin/templates/admin`
```
and configure sphinx to convert this markup to github links?

2022-06-30 17:41 UTC, felixxm commented
@rayman1104 Thanks for this patch :+1: You should use the `:source:` directive.

2022-07-01 09:01 UTC, ngnpope requested changes
We already have the [`:source:`](https://github.com/django/django/blob/5c93a84f44054034f495267ff2400a5de69a4fc1/docs/conf.py#L133-L134) role for this to make it quick and easy.

We do use the `:file:` role in many other places. It'd be good to audit them and determine which would be useful converted to `:source:`.

However, maybe we should use [`:file:`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-file) (which can be used for directories) instead for many of these cases and not link. My concern is that we'd be pointing people to the templates (or other resources) on the `main` branch which might conceivably be incompatible with the version of Django they are using... Perhaps it is better if they have to manually find it? 🤔

There are also many paths and directories that don't use either `:file:` or `:source:` which could be fixed up if you're willing to find them. A good starting point for strings to consider would be the output of the following command:

```console
$ git grep --extended-regexp '``(~|django|docs|extras|js_tests|scripts|tests)?/[^`]+``' docs/
```

2022-07-02 23:22 UTC, rayman1104 commented
> We do use the :file: role in many other places. It'd be good to audit them and determine which would be useful converted to :source:.

Should be fixed now, thanks!

> There are also many paths and directories that don't use either :file: or :source: which could be fixed up if you're willing to find them.

Should be fixed now, thanks!

> My concern is that we'd be pointing people to the templates (or other resources) on the main branch which might conceivably be incompatible with the version of Django they are using... Perhaps it is better if they have to manually find it? 🤔

Should we change the link for the [`:source:`](https://github.com/django/django/blob/5c93a84f44054034f495267ff2400a5de69a4fc1/docs/conf.py#L133-L134) role then? To smth like
```
"source": (f"https://github.com/django/django/blob/stable/{version}.x/%s", "%s"),
```

2022-07-08 15:29 UTC, rayman1104 commented
@ngnpope @felixxm please review.

2022-07-14 09:45 UTC, carltongibson reviewed
Hmmm. 😕 I think I'm going to disagree with what @ngnpope said in https://github.com/django/django/pull/15808#pullrequestreview-1025908818. 

* I think the `:source:` link is worth having, even for directories, as it's clickable and points folks to GitHub. 
    *  Maybe there's a case for making it version dependent, so we point the `stable/3.2.x` branch for Django 3.2... 
    * ... but I think taking away the link (or not adding it) defeats the purpose of the ticket, which was to have a clickable link that you can follow for more details. 
* I don't see the benefit of switching from backticks to `:file:` in general. It seems more verbose for no gain. 🤔 (The only cases I thought, _Oh yes_ about were those removing the `:file:` usage — on URL fragments — in the syndication docs. ) 

My suggestion would be `:source:` for everything in `django/django` — unless there's a specific reason why not — and the backticks for everything else. Thoughts?

2022-07-14 09:45 UTC, carltongibson commented on docs/howto/deployment/wsgi/modwsgi.txt
> +    A common location to put this configuration is :file:`/etc/apache2/envvars`.
???

2022-07-14 09:45 UTC, carltongibson commented on docs/intro/contributing.txt
> +Navigate to the :file:`django/` folder and open the ``shortcuts.py`` file. At the
Why can't (all?) the cases in this file be `:source:`? (They're actual files in django/django repository.) 🤔

2022-07-14 09:45 UTC, carltongibson commented on docs/intro/tutorial07.txt
> +    project's (:file:`templates`). We'll discuss in more detail in the
I'm not sure of the value of using `:file:` in all these cases? (It seems more verbose for no gain...) 🤔

2022-07-20 14:28 UTC, rayman1104 commented
@carltongibson thanks for review!

> * I don't see the benefit of switching from backticks to `:file:` in general. It seems more verbose for no gain. 🤔 (The only cases I thought, _Oh yes_ about were those removing the `:file:` usage — on URL fragments — in the syndication docs. )

Well, I'm new here. And I don't understand the purpose of having `:file:` tag at all. But there are 2 reasons why I've added it everywhere. First is the comments above and second is [this line in the docs](https://docs.djangoproject.com/en/4.0/internals/contributing/writing-documentation/#guidelines-for-restructuredtext-files):
> The main thing to keep in mind as you write and edit docs is that the more semantic markup you can add the better.

And then there is some example and they say that having backticks _isn’t nearly as helpful_ as having semantic markup.

But yeah, if you confirm that `:file:` tag is useless, than it's not just me, so I can get rid of it everywhere and just use backticks.

2022-08-09 13:02 UTC, carltongibson approved these changes
Thanks for the effort here @rayman1104! 🎁

I've rebased, and collected the changes into three separate commits. 

I dropped the suggested changes to `contributing.txt` because at that point we are explicitly talking about the user's local checkout, and giving instructions such as `cd tests`, where I thought linking to the repo was actually a distraction. I've copied that below for posterity. 

Welcome aboard! ⛵ 

<details>
<summary>patch for contributing.txt changes</summary>


```diff
From 0720b169f7f3eee40ce8225505db87e3d43bbb8c Mon Sep 17 00:00:00 2001
From: Ramil Yanbulatov <rayman1104@gmail.com>
Date: Tue, 9 Aug 2022 14:45:09 +0200
Subject: [PATCH] fixup! Fixed #33842 -- Used :source: role for links to repo
 files on GitHub.

---
 docs/intro/contributing.txt | 16 ++++++++--------
 1 file changed, 8 insertions(+), 8 deletions(-)

diff --git a/docs/intro/contributing.txt b/docs/intro/contributing.txt
index 0953ff7182..d25e6d0e58 100644
--- a/docs/intro/contributing.txt
+++ b/docs/intro/contributing.txt
@@ -199,7 +199,7 @@ work and haven't broken other parts of Django. If you've never run Django's test
 suite before, it's a good idea to run it once beforehand to get familiar with
 its output.

-Before running the test suite, enter the Django ``tests/`` directory using the
+Before running the test suite, enter the Django :source:`tests/` directory using the
 ``cd tests`` command, and install test dependencies by running:

 .. console::
@@ -317,7 +317,7 @@ In order to resolve this ticket, we'll add a ``make_toast()`` function to the
 ``django.shortcuts`` module. First we are going to write a test that tries to
 use the function and check that its output looks correct.

-Navigate to Django's ``tests/shortcuts/`` folder and create a new file
+Navigate to Django's :source:`tests/shortcuts/` folder and create a new file
 ``test_make_toast.py``. Add the following code::

     from django.shortcuts import make_toast
@@ -350,7 +350,7 @@ Running your new test

 Since we haven't made any modifications to ``django.shortcuts`` yet, our test
 should fail. Let's run all the tests in the ``shortcuts`` folder to make sure
-that's really what happens. ``cd`` to the Django ``tests/`` directory and run:
+that's really what happens. ``cd`` to the Django :source:`tests/` directory and run:

 .. console::

@@ -369,7 +369,7 @@ Writing the code for your ticket

 Next we'll be adding the ``make_toast()`` function.

-Navigate to the ``django/`` folder and open the ``shortcuts.py`` file. At the
+Navigate to the :source:`django/` folder and open the ``shortcuts.py`` file. At the
 bottom, add::

     def make_toast():
@@ -377,7 +377,7 @@ bottom, add::

 Now we need to make sure that the test we wrote earlier passes, so we can see
 whether the code we added is working correctly. Again, navigate to the Django
-``tests/`` directory and run:
+:source:`tests/` directory and run:

 .. console::

@@ -395,7 +395,7 @@ hasn't introduced any bugs into other areas of Django. While successfully
 passing the entire test suite doesn't guarantee your code is bug free, it does
 help identify many bugs and regressions that might otherwise go unnoticed.

-To run the entire Django test suite, ``cd`` into the Django ``tests/``
+To run the entire Django test suite, ``cd`` into the Django :source:`tests/`
 directory and run:

 .. console::
@@ -406,7 +406,7 @@ Writing Documentation
 =====================

 This is a new feature, so it should be documented. Open the file
-``docs/topics/http/shortcuts.txt`` and add the following at the end of the
+:source:`docs/topics/http/shortcuts.txt` and add the following at the end of the
 file::

     ``make_toast()``
@@ -420,7 +420,7 @@ file::

 Since this new feature will be in an upcoming release it is also added to the
 release notes for the next version of Django. Open the release notes for the
-latest version in ``docs/releases/``, which at time of writing is ``2.2.txt``.
+latest version in :source:`docs/releases/`, which at time of writing is ``2.2.txt``.
 Add a note under the "Minor Features" header::

     :mod:`django.shortcuts`
--
2.36.1
```

</details>

2022-08-09 13:26 UTC, merged

2022-10-11 08:41 UTC, piw2266 commented
장

2022년 7월 3일 (일) 08:24, Ramil Yanbulatov ***@***.***>님이 작성:

> We do use the :file: role in many other places. It'd be good to audit them
> and determine which would be useful converted to :source:.
>
> Should be fixed now, thanks!
>
> There are also many paths and directories that don't use either :file: or
> :source: which could be fixed up if you're willing to find them.
>
> Should be fixed now, thanks!
>
> My concern is that we'd be pointing people to the templates (or other
> resources) on the main branch which might conceivably be incompatible with
> the version of Django they are using... Perhaps it is better if they have
> to manually find it? 🤔
>
> Should we change the link for the :source:
> <https://github.com/django/django/blob/5c93a84f44054034f495267ff2400a5de69a4fc1/docs/conf.py#L133-L134>
> role then? To smth like
>
> "source": (f"https://github.com/django/django/blob/stable/{version}.x/%s", "%s"),
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/django/django/pull/15808#issuecomment-1172977414>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXGZZLIYQCWFNTFNUBHZETLVSDFRDANCNFSM52JHPJWA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>