new #10088 -- Added share lock for QuerySet
django/django pull request #16172
Opened 2022-10-12 01:53 UTC by smartofmarked

2022-10-14 11:21 UTC, kezabelle commented
Hi @smartofmarked, thank you for opening this. I've just updated the ticket ([10088](https://code.djangoproject.com/ticket/10088)) to add the `has patch` flag -- beyond that, please be patient. I'm sure it will get looked at as soon as someone has the bandwidth to do so.

2022-10-14 15:16 UTC, smartofmarked commented
[kezabelle](https://github.com/kezabelle) , thanks very much , i am so new,  and english so new to , but i am very interested for this, If I do something wrong, please tell me , I promise I'll try do it

2022-12-13 07:38 UTC, auvipy commented
please comment on the related ticket and uncheck patch need improvement to make this into review Q

2022-12-13 07:43 UTC, auvipy requested changes

2022-12-13 07:43 UTC, auvipy commented on docs/releases/4.2.txt
> +
you probably should add some detail here about the feature

2022-12-13 07:43 UTC, auvipy commented on docs/topics/db/queries.txt
> +select_for_share
this might need version added 4.2 annotation

2022-12-13 18:26 UTC, ngnpope commented
See #16381 for a more complete implementation.

2022-12-13 18:26 UTC, closed without merging