Fixed #12241 Admin forgets URL used for prefilling forms when hitting Save and add another
django/django pull request #16206
Opened 2022-10-20 21:42 UTC by matthewn

https://code.djangoproject.com/ticket/12241

Ensure querystring persists when 'save and add another' is clicked. Add a test case.

Co-authored-by: Grady Yu <gradyy@users.noreply.github.com>

2022-10-22 05:42 UTC, shangxiao requested changes
Way to go to fix a decade-old issue ♥️

I have a suggestion there to:

- Update format to black standards
- Use the walrus operator

Just FYI in case you're not familiar with Black - it's a really useful auto-formatter that you can use to deal with the tedium of formatting. You can usually get something to integrate with your editor/IDE of choice and have it automatically do it on save 🙂

2022-10-22 05:42 UTC, shangxiao commented on django/contrib/admin/options.py
> +                redirect_url += f'?{query_string}'
```suggestion
            if query_string := request.GET.urlencode():
                redirect_url += f"?{query_string}"
```

2022-10-22 05:49 UTC, shangxiao commented
Also I'd argue that since this is a decade-old issue, that preserving the querystring for save-and-continue-editing may not be an important issue to solve?

2022-10-24 21:05 UTC, matthewn commented
Thank you kindly for the code suggestions.

As for save-and-continue, I don't understand the use case there. Persisting prefilled values makes sense for save-and-add: I can imagine wanting to input numerous records with one or more values already filled in. But I don't see how persisting prefilled values would be useful when you work with one record and click to save-and-continue. (If there is a use case I'm not thinking of, I'm happy to implement that feature too before the ticket closes.)

2022-10-25 00:12 UTC, shangxiao commented
> Thank you kindly for the code suggestions.
> 
> As for save-and-continue, I don't understand the use case there. Persisting prefilled values makes sense for save-and-add: I can imagine wanting to input numerous records with one or more values already filled in. But I don't see how persisting prefilled values would be useful when you work with one record and click to save-and-continue. (If there is a use case I'm not thinking of, I'm happy to implement that feature too before the ticket closes.)

Yep 👍  Even if the issue is still relevant I'd wager a member of the merging team would happily accept this patch.

There's still an issue with Black needing to be run on the tests – if you're happy to fix that, squash the commits up then it should be good to pass on for final review by marking the ticket status to "Ready for checkin".

2022-10-25 17:37 UTC, matthewn commented
@shangxiao please forgive my ignorance, can you enlighten me on the best method for squashing the commits in this pull request? I tried doing that locally and pushing back up but GitHub complained ("the tip of your current branch is behind its remote counterpart"), so I'm sitting here wondering how to squash without screwing up what is already here. Thank you for helping a newbie. :)

2022-10-26 02:44 UTC, shangxiao commented
@matthewn Rebasing, squashing & general editing of commits requires a force push because there's a new commit path that's been created in the process:

```
git push --force <remote> <branch-name>
```

2022-10-27 11:35 UTC, felixxm commented
@matthewn Thanks for this patch :+1: 

> As for save-and-continue, I don't understand the use case there. Persisting prefilled values makes sense for save-and-add: I can imagine wanting to input numerous records with one or more values already filled in. But I don't see how persisting prefilled values would be useful when you work with one record and click to save-and-continue. (If there is a use case I'm not thinking of, I'm happy to implement that feature too before the ticket closes.)

As far as I'm aware, we should preserve query strings for "Save and continue" as well. I can imagine valid use cases, e.g. pre-filtering `<select>` lists based on the passed values.

2022-11-07 22:03 UTC, matthewn commented
I've expanded my fix to cover save-and-add and save-and-continue on both add and change forms. Four tests cover the four cases.

2022-11-08 08:54 UTC, felixxm commented
@matthewn Thanks :+1: However this solutions doesn't work with popups or preserved filters that are already in the query strings, e.g.

https://user-images.githubusercontent.com/2865885/200519188-b233e25a-e5cd-4351-8303-9de1d0e2eef5.mp4

I simplified tests.

2022-11-08 19:41 UTC, matthewn commented
Hello @felixxm, thank you for the revised tests.

I am not certain I understand your new request. Is it that the _popup and _changelist_filters parameters should not persist when the buttons are clicked?

Separately: Am I right to have applied this fix to the change form as well as the add form? Since change forms don't prefill values like add forms do, I'm not understanding why this is useful.

Would love to see this PR through to completion, just feeling a bit confused at the moment!

2022-11-08 19:54 UTC, felixxm commented
> I am not certain I understand your new request. Is it that the _popup and _changelist_filters parameters should not persist when the buttons are clicked?

There are few things from the query string that are preserved even without this patch i.e. `_changelist_filters`, `_popup`, and `_to_field` (see how `get_preserved_filters()` and `add_preserved_filters()` work). This should still work.

With this patch a  query string is incorrectly changed from `?changelist_filters=is_staff__exact%3D1` to `?changelist_filters=is_staff__exact%3D1?changelist_filters=is_staff__exact%3D1`. We could encapsulate remaining GET parameters and pass them in `opts` to `add_preserved_filters()` :thinking: .

> Separately: Am I right to have applied this fix to the change form as well as the add form?

Yes :+1:

2022-12-15 07:32 UTC, felixxm commented
@matthewn Do you have time to keep working on this?

2022-12-15 17:46 UTC, matthewn commented
@felixxm Yes, I anticipate being able to take another run at this soon.

2023-01-07 00:24 UTC, matthewn commented
@felixxm  -- I've taken another pass at this. (My employer lets me hack on Django on Friday afternoons for the time being, so that's when I get to dive deep on this.)

I am now encapsulating non-preserved qs params and passing them into the context fed to add_preserved_filters(), where I ensure they get included in the returned url. This makes the tests pass, and also makes all the manual use-cases I've been testing behave as I expect.

But it all goes wrong when a preserved filter enters the mix. Take /admin/auth/user/2/change/?last_name=foobar&_changelist_filters=is_active__exact%3D1 for example. When you save from there, the changelist filters are now getting preserved properly, but the additional qs pair is being lost, and I am stumped as to where that is happening.

Would appreciate it if you could tell me whether you think this latest attempt is on the right track, and if so, where I need to look more deeply to understand the last bit of trouble. Thank you most kindly for being patient with me!

2023-01-25 07:39 UTC, felixxm commented
> But it all goes wrong when a preserved filter enters the mix. Take /admin/auth/user/2/change/?last_name=foobar&_changelist_filters=is_active__exact%3D1 for example. When you save from there, the changelist filters are now getting preserved properly, but the additional qs pair is being lost, and I am stumped as to where that is happening.

It seems we also need to add `preserved_qsl` in the `render_change_form()`.

2023-01-25 07:43 UTC, felixxm commented on django/contrib/admin/options.py
> +            preserved_qsl = parse_qsl(query_string.replace(preserved_filters, ""))
Can we move this to a separate hook? Should we also remove `_popup` and `_to_field`?

2023-01-25 07:44 UTC, felixxm commented on tests/admin_views/tests.py
> +
We need tests for the query string with `_changelist_filters`, `_popup`, and `_to_field`.

2023-05-15 10:50 UTC, felixxm commented
Closing due to inactivity.

2023-05-15 10:50 UTC, closed without merging