#34234 Drop support for PROJ < 5.
django/django pull request #16445
Opened 2023-01-11 17:30 UTC by select-case

2023-01-12 07:47 UTC, claudep requested changes
Thanks! You should also add a note in the release notes. I think we could also simplify a bit in `tests/gis_tests/test_spatialrefsys.py` (near the top of the file).

2023-01-12 12:25 UTC, felixxm commented on docs/releases/4.2.txt
> +
Please revert this unrelated change.

2023-01-12 12:26 UTC, felixxm commented on tests/gis_tests/test_spatialrefsys.py
> -        # +ellps=WGS84 has been removed in the 4326 proj string in proj-4.8
It's not only about the comment, we should update `proj_re` and related tests.

2023-01-13 11:32 UTC, felixxm commented
@select-case Thanks :+1: I pushed edits.

2023-01-13 17:17 UTC, claudep approved these changes
:+1:

2023-01-13 17:59 UTC, felixxm commented
@claudep Thanks for checking :+1:

2023-01-13 18:01 UTC, merged