Fixes #34370 -- Fix overflow error in sqlite with integers.
django/django pull request #16601
Opened 2023-02-27 03:28 UTC by nabil-rady

Fixes [34370](https://code.djangoproject.com/ticket/34370)

2023-02-27 03:38 UTC, mina-atef-00 requested changes
could you add typing?

2023-02-27 04:12 UTC, felixxm commented
> could you add typing?

We currently don't use type annotations.

2023-02-27 04:43 UTC, felixxm reviewed
@nabil-rady Thanks :+1:

2023-02-27 04:43 UTC, felixxm commented on django/db/backends/sqlite3/operations.py
> -        return (None, None)
To keep this as backward compatible as we can we should use `[2**63, 2**63 - 1]` for all types.

Also, a release note in backward incompatible changes is missing.

2023-02-27 04:43 UTC, felixxm commented on tests/model_fields/test_integerfield.py
> +            instance_underflow.full_clean()
This line is unreachable.

2023-02-28 07:44 UTC, felixxm commented on django/db/backends/sqlite3/operations.py
> +        return (-9223372036854775808, 9223372036854775807)
I'd use:
```python
def integer_field_range(self, internal_type):
    if internal_type in ["PositiveBigIntegerField", "PositiveSmallIntegerField", "PositiveIntegerField"]:
        return (0, 9223372036854775807)
    return (-9223372036854775808, 9223372036854775807)
```

2023-02-28 07:44 UTC, felixxm commented on tests/model_fields/test_integerfield.py
> +        if max_value <= max_documented_value:
Changes in `test_backend_range_save` looks unnecessary, please revert.

2023-02-28 07:44 UTC, felixxm commented on tests/model_fields/test_integerfield.py
> +            instance_overflow.full_clean()
`test_overflow_and_underflow` seems unnecessary, it's already tested in `test_backend_range_validation`.

2023-03-01 12:21 UTC, felixxm commented on tests/model_fields/test_integerfield.py
> +        self.assertIsInstance(model_validators[1], validators.MaxValueValidator)
This can fail for 3rd-party database backends. I don't there is any need for additional tests in this patch.

2023-03-08 11:01 UTC, felixxm reviewed
@nabil-rady Thanks :+1: I added a release note.

2023-03-08 12:00 UTC, merged