WIP: Updated GDAL API to handle vector DataSource's
django/django pull request #16650
Opened 2023-03-13 17:40 UTC by claudep

2023-03-15 17:36 UTC, Aliquoted commented
`django/contrib/gis/gdal/datasource.py `
has a comment on line 72. Comments must have a space after the #.

`django/contrib/gis/gdal/prototypes/ds.py`
imports ctypes.c_uint on line 6 but never uses it.
has 89 characters on line 42 but the limit is 88.

Fixing these should make your PR pass flake8.

2023-03-15 17:41 UTC, Aliquoted requested changes
`django/contrib/gis/gdal/datasource.py `
has a comment on line 72. Comments must have a space after the #.

`django/contrib/gis/gdal/prototypes/ds.py`
imports ctypes.c_uint on line 6 but never uses it.
has 89 characters on line 42 but the limit is 88.

Fixing these should make your PR pass flake8.

2023-03-15 17:46 UTC, claudep commented
Thanks, but I'm not interested to make this PR pass flake8 for the time being. This is related to https://code.djangoproject.com/ticket/34411. I'd like to make the OGROpen -> GDALOpenEx switch, but it's not trivial to do and hope to get help from someone with C interfaces experience.

2023-03-17 02:17 UTC, Aliquoted commented
Right. PEP8 is gospel to some and quality theatre to others so that is a classic dispute. However, to preempt complaints from the evangelists I think it is wise to make the changes. Your call.

2023-10-04 19:29 UTC, smithdc1 commented
I managed to make some progress some time ago on switching to `OpenEx`  https://github.com/smithdc1/django/commit/144da07684064aea4a27f446d08f229d4b60b2c9.

While I could get the test suite to pass with this, there's one bit that I'm unsure on which is noted in the comments. 

Sorry, I don't have time _right now_ to work on this further.

2023-12-16 15:41 UTC, claudep commented
Thanks a lot @smithdc1, I was able to make significant progresses with your suggested commit.

I'm still having issues with getting a layer name with a PostgreSQL data source, as the tests show (gis_tests.inspectapp.tests.OGRInspectTest.test_time_field).

2023-12-17 09:36 UTC, smithdc1 commented on django/contrib/gis/gdal/datasource.py
> +                ds = capi.open_ds(force_bytes(ds_input), self._write, None, None, None)
Stepping through `gis_tests.inspectapp.tests.OGRInspectTest.test_time_field` before this patch I see:
```
(Pdb) ds
c_void_p(2751523152928)
(Pdb) capi.get_layer_count(ds)
49
(Pdb) ds_input
"PG:dbname='test_geodjango' user='postgres' password='david'"
(Pdb) capi.get_ds_name(ds)
b"PG:dbname='test_geodjango' user='postgres' password='david'"
```

with this patch I see:

```
(Pdb) ds
c_void_p(2276731897056)
(Pdb) capi.get_layer_count(ds)
0
(Pdb) ds_input
"PG:dbname='test_geodjango' user='postgres' password='david'"
(Pdb) capi.get_ds_name(ds)
b"PG:dbname='test_geodjango' user='postgres' password='david'"
(Pdb)
```

It seems there is an issue with opening the datasource? 🤔

2023-12-17 14:54 UTC, claudep commented on django/contrib/gis/gdal/datasource.py
> +                ds = capi.open_ds(force_bytes(ds_input), self._write, None, None, None)
https://gis.stackexchange.com/questions/207415/no-layers-after-connected-to-postgres-using-gdal-2-1-c-api may give some hints

2023-12-17 15:02 UTC, claudep commented on django/contrib/gis/gdal/datasource.py
> +                ds = capi.open_ds(force_bytes(ds_input), self._write, None, None, None)
I can confirm that when we open the datasource with GDAL_OF_VECTOR param, the layers are suddenly visible!

2023-12-17 17:01 UTC, smithdc1 commented on django/contrib/gis/gdal/datasource.py
> +                    self._write | capi.GDAL_OF_VECTOR,
Is this always a vector?

2023-12-17 22:02 UTC, claudep commented on django/contrib/gis/gdal/datasource.py
> +                    self._write | capi.GDAL_OF_VECTOR,
I think so, because raster data sources are handled through `GDALRaster` classes in the current code layout. I guess that in the future, some harmonization may take place and then we might reconsider this.

2023-12-18 04:53 UTC, felixxm commented
Thanks for all your efforts :star2: Can we rename it to `Fixed ...`? or there is more work to be done :thinking:

2023-12-18 07:16 UTC, claudep commented
I was not sure at first if we should do more to unify raster and vector sources, but let's say we can always open new tickets if at some point we estimate that more work should we done.

2023-12-18 08:42 UTC, felixxm approved these changes

2023-12-18 09:20 UTC, merged