Prevent crash if sqlite3 is configured using a PosixPath
django/django pull request #16824
Opened 2023-05-03 12:26 UTC by jieter

With a sqlite database configured in `settings.py` like this:
```python
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
```
exiting `./manage.py dbshell` using <kbd>Control</kbd>-<kbd>d</kbd> sometimes results in this exception:

```
Traceback (most recent call last):
  File "/home/ubuntu/virtualenv/lib/python3.11/site-packages/django/core/management/commands/dbshell.py", line 30, in handle
    connection.client.runshell(options["parameters"])
  File "/home/ubuntu/virtualenv/lib/python3.11/site-packages/django/db/backends/base/client.py", line 28, in runshell
    subprocess.run(args, env=env, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sqlite3', PosixPath('/home/ubuntu/planning-poker/db.sqlite3')]' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/planning-poker/./manage.py", line 30, in <module>
    main()
  File "/home/ubuntu/planning-poker/./manage.py", line 26, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/virtualenv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/virtualenv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/virtualenv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/virtualenv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/virtualenv/lib/python3.11/site-packages/django/core/management/commands/dbshell.py", line 44, in handle
    " ".join(e.cmd),
    ^^^^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, PosixPath found
```

coercing each item in `e.cmd` to string should fix this.

(Please let me know if a trac ticket is required)

2023-05-03 12:37 UTC, shangxiao commented
Nice catch. Yes a ticket will need to be created please.

A test will also be required.

I'm wondering whether the docs could be updated to state that a `Path` may be acceptable for sqlite as there's a small warning about windows users and `Path` may be a nicer choice here.

2023-05-03 13:38 UTC, shangxiao commented
@jieter Also the commit message will need to refer to the ticket, please see the commit log for the required format (all in past tense too please)

2023-05-03 14:28 UTC, jieter commented
> A test will also be required.
A test was added to the patch.

 
> I'm wondering whether the docs could be updated to state that a `Path` may be acceptable for sqlite as there's a small warning about windows users and `Path` may be a nicer choice here.

I think you refer to this?

https://github.com/django/django/blob/49830025c992fbc8d8f213e7c16dba1391c6adf2/docs/ref/settings.txt#L591-L593

If we were to change that, there is a similar note for `STATICFILES_DIRS` in that file.

In `intro/tutorial2.txt` using a `Path` is already (implicitly) suggested:
https://github.com/django/django/blob/49830025c992fbc8d8f213e7c16dba1391c6adf2/docs/intro/tutorial02.txt#L42

2023-05-03 14:44 UTC, jieter commented
The test fail in some environments. Should I fix that with `override_settings`/`skipIf`?

2023-05-03 16:18 UTC, shangxiao requested changes
🏆 Thanks for doing this! ❤️

2023-05-03 16:18 UTC, shangxiao commented on tests/dbshell/test_sqlite.py
> +            "django.db.backends.sqlite3.client.DatabaseClient.runshell", new=raise_error
We can raise directly with patch like so (tested locally):

```suggestion
        expected_message = '"sqlite3 test.db.sqlite3" returned non-zero exit status 1.'
        with mock.patch(
            "django.db.backends.sqlite3.client.DatabaseClient.runshell",
            side_effect=subprocess.CalledProcessError(returncode=1, cmd=cmd),
```

2023-05-03 16:24 UTC, shangxiao commented
> If we were to change that, there is a similar note for STATICFILES_DIRS in that file.

Ah I see what you mean yep.

Thinking about it, it might be better off as a separate doc PR. Someone may have a better way of updating it, eg if there was a general tip somewhere to refer to that talked about paths, Windows & using Path.

2023-05-03 19:15 UTC, jieter commented
@shangxiao Thanks for the suggestions, all checks green now.

2023-05-04 04:09 UTC, felixxm commented
@jieter Thanks :+1: I pushed tiny edits to the test.

2023-05-04 05:55 UTC, merged

2023-05-05 15:34 UTC, adamchainz commented
Thanks for the fix!