Fixed 9519 -- Add QuerySet.bulk_delete() that issues minimum queries
django/django pull request #16924
Opened 2023-06-02 08:10 UTC by Akash-Kumar-Sen

2023-06-04 19:39 UTC, LilyFoote requested changes
Looks like a good start to me!

It should be decoupled from the changes for #16907 with a rebase to remove those commits.

2023-06-04 19:39 UTC, LilyFoote commented on django/db/models/deletion.py
> +        # set perform_signals to false in order to ignore signals
I think this is sufficiently clear from the name `perform_signals` that we don't need this comment.

2023-06-04 19:39 UTC, LilyFoote commented on django/db/models/deletion.py
> +                    fail_on_restricted=False,
I don't see a reason for this formatting change.

2023-06-04 19:39 UTC, LilyFoote commented on django/db/models/query.py
> +    bulk_delete.queryset_only = True
Given the implementation of this method is identical to that of `delete`, except for setting `perform_signals=False` in `Collector`, I think we should either merge the two methods or delegate the implementation of each to a new private method (`_delete` perhaps).

2023-06-04 19:39 UTC, LilyFoote commented on tests/test_bulk_deletion/tests.py
> +    def setDown(self):
```suggestion
    def tearDown(self):
```

2023-06-04 19:39 UTC, LilyFoote commented on tests/test_bulk_deletion/tests.py
> +        self.post_delete_signal_was_called = False
These are never used.

2023-06-04 19:39 UTC, LilyFoote commented on tests/test_bulk_deletion/tests.py
> +        self.setDown()
```suggestion
```

2023-06-04 19:39 UTC, LilyFoote commented on tests/test_bulk_deletion/tests.py
> +        self.setDown()
```suggestion
```

2023-06-04 19:39 UTC, LilyFoote commented on tests/test_bulk_deletion/tests.py
> +            foo_objs.bulk_delete()
```suggestion
            Foo.objects.filter(pk=foo.pk).bulk_delete()
```

2023-06-04 19:39 UTC, LilyFoote commented on tests/test_bulk_deletion/tests.py
> +            foo_objs.delete()
```suggestion
            Foo.objects.filter(pk=foo.pk).delete()
```

2023-06-04 19:39 UTC, LilyFoote commented on tests/test_bulk_deletion/tests.py
> +                Baz.objects.create(bar=bar)
It may make sense to move this into `setUp`.

2023-06-05 01:58 UTC, Akash-Kumar-Sen commented
Thank you for the valuable suggestions @LilyFoote 

> It should be decoupled from the changes for #16907 with a rebase to remove those commits.

This seems redundant as I have already resolved the conflicts. Github will squash all the commits and treat the whole PR as a single commit, Other propositions seems helpful, will update the PR accordingly.

2023-06-05 04:14 UTC, felixxm commented
Closing per ticket.

2023-06-05 04:14 UTC, closed without merging