Fixed #28050 -- Included template name in TemplateSyntaxError.
django/django pull request #16937
Opened 2023-06-03 09:42 UTC by tim-mccurrach

https://code.djangoproject.com/ticket/28050

I came across this about a month back whilst looking through some production logs. Effort has clearly been made to make the error messages useful, and indicating line numbers is a great initiative. But sadly, without the actual template name, this effort becomes nullified. This is made worse when there are multiple `{% include %}`s, making it difficult to figure out which template is referenced.

There have been a few attempts at this ticket before:
 - #8332
 - #8929 (which then became #8974)

The major complaint with the above PRs was: with the template name included in the exception message, the debug view became cluttered and other places where the template name is explicitly listed become redundant. In my view, the value added by including the template name in the error message far outweighs the disadvantage of any additional clutter in the debug view.

None-the-less, there are several ways to achieve the objective of the ticket without cluttering the debug view.

### Approach 1
 - We record the original error message, and add it as an attribute to the exception. The debug page uses the original message if it can.

### Approach 2
 - Only add the template name when debug is off. This way you get useful messages for production logs, sentry etc. However, concerns about the debug page won't matter since this would only be displayed with debug on anyway.

Approach 2 is a lot simpler, however I'm not sure how I feel about introducing additional differences in logic between debug on and off. Especially within core error handling logic. This feels like a recipe for hard-to-debug problems.

2023-06-13 05:07 UTC, shangxiao requested changes
Nice work picking this up, interesting approach you've used. felix or nessita will have the final say on whether this approach is the way forward.

A couple of more points:
 - As an alternative TemplateSyntaxError could probably declare the attribute by default. It could also potentially get a prop/method to return the "debug message"?
 - felix has marked this PR as requiring tests on the ticket

2023-06-13 05:07 UTC, shangxiao commented on django/template/base.py
> +                    pass
Can't we catch `TemplateSyntaxError` instead of try/excepting `e.args` access? 🤔

2023-06-13 05:07 UTC, shangxiao commented on django/template/base.py
> +                    e.args = (template_path + raw_message, *e.args[1:])
There's a string interpolation + concat, I feel like we can minimise this to a single interpolation 🤔

2023-06-13 05:07 UTC, shangxiao commented on django/views/debug.py
> +                c["exception_value"] = str(self.exc_value)
Looks like this is equivalent?
```suggestion
            c["exception_value"] = getattr(self.exc_value, "raw_template_error_message", self.exc_value)
```

2024-12-01 22:43 UTC, jacobtylerwalls commented
Closing due to inactivity, but feel free to reopen if you can pursue it further.

2024-12-01 22:43 UTC, closed without merging