Fixed #34779 -- Remove unnecessary select_related joins when serializing objects
django/django pull request #17164
Opened 2023-08-15 19:58 UTC by jualvarez

By using `select_related(None)` instead of `select_related()`, the unnecessary joins are avoided.
Note that the current tests already covers the change, when the field is not `null=True`.

2023-08-16 04:19 UTC, auvipy requested changes
I think you also need to check the test failures in the CI, as the proposed changes are breaking the tests

2023-08-18 16:25 UTC, felixxm commented on docs/releases/4.2.2.txt
> +  serialization with M2M fields ``select_related()`` (:ticket:`34779`).
Move this to the `4.2.5.txt`:
```suggestion
* Fixed a regression in Django 4.2.2 that caused ...
```

2023-08-18 21:23 UTC, jualvarez commented on docs/releases/4.2.2.txt
> +  serialization with M2M fields ``select_related()`` (:ticket:`34779`).
Newbie mistake :) 
Updated!

2023-08-19 08:30 UTC, felixxm commented
@jualvarez Thanks :+1: Welcome aboard :boat: 

I pushed edits to a release note.

2023-08-19 09:23 UTC, merged