Avoided counting exception in AsynClient docs.
django/django pull request #17190
Opened 2023-08-23 19:22 UTC by felixxm

Follow up to ad6bb20557f5c87de26aeb3afb061af942a8cc17.

2023-08-23 19:23 UTC, felixxm commented on docs/topics/testing/tools.txt
> +test client, with the following exceptions:
Now we have three exceptions :smile:

2023-08-23 19:25 UTC, jacobtylerwalls approved these changes

2023-08-23 19:35 UTC, nessita approved these changes
LGTM

2023-08-23 19:45 UTC, ngnpope requested changes
LGTM, but fix `AsynClient` → `AsyncClient` in PR title / commit message.

2023-08-24 03:19 UTC, felixxm commented
Thanks y'all :+1:

2023-08-24 03:19 UTC, merged