Fixed #12241 -- Preserved query strings when using "Save and continue/add another" in admin
django/django pull request #17194
Opened 2023-08-24 22:11 UTC by marianaasilva

Fix for [ticket 12241](https://code.djangoproject.com/ticket/12241) to ensure the query string is preserved when clicking "Save and add another" or "Save and continue"

Added tests for query string with changelist filters

_Based on @matthewn's patch [pr/16206](https://github.com/django/django/pull/16206)_

2023-08-29 20:18 UTC, LilyFoote requested changes
Nice to see progress on this!

I see that we also have `_saveasnew` in `response_change` - is this deliberately handled differently? I see it's bundled with the `_continue` handling in `response_add`, so we're changing the behaviour there.

Either way, I think we should add tests for this case too.

2023-09-09 00:12 UTC, marianaasilva commented
> Nice to see progress on this!
> 
> I see that we also have `_saveasnew` in `response_change` - is this deliberately handled differently? I see it's bundled with the `_continue` handling in `response_add`, so we're changing the behaviour there.
> 
> Either way, I think we should add tests for this case too.

@LilyFoote Thank you for the feedback 😄

After looking more closely into this, I believe the `_saveasnew` condition in `response_change` is never reached? From what I understood, the `response_add` and `response_change` methods get called in `_changeform_view` but if the request method is a **POST** and `_saveasnew` is present in the request data, it will always default to `response_add`

2023-09-09 21:00 UTC, LilyFoote commented
I think you're right! In that case I think it's reasonable to delete the unreachable code. Though perhaps in a separate PR. @felixxm @nessita Thoughts?

For this PR, I still think we should add a test for preserving the query strings (or explicitly not preserving them) for the `_saveasnew` option in `response_add`, since that *is* reachable if I understand correctly.

2023-09-10 19:51 UTC, marianaasilva commented
> I think you're right! In that case I think it's reasonable to delete the unreachable code. Though perhaps in a separate PR. @felixxm @nessita Thoughts?
> 
> For this PR, I still think we should add a test for preserving the query strings (or explicitly not preserving them) for the `_saveasnew` option in `response_add`, since that _is_ reachable if I understand correctly.

Makes sense! Already updated the tests to include the `_saveasnew` option. Thank you!

2023-09-19 13:43 UTC, LilyFoote approved these changes

2023-09-19 14:25 UTC, shangxiao approved these changes
(Adding my 2¢ since I looked at the previous PR)

Just tested it out, looks nice 🏆

I didn't really read the code in anger although the only thing that catches my eye is "qsl" which made me wonder what it meant … eventually saw the docs for `parse_qsl()` as returning list.

2023-09-27 03:40 UTC, felixxm commented
@marianaasilva Thanks :+1: Have you checked how it works with options that are currently preserved (`_changelist_filters`, `_popup`, and `_to_field`)? We should add tests for them, check out https://github.com/django/django/pull/16206#discussion_r1086298285.

2023-10-09 03:38 UTC, felixxm commented on tests/admin_views/tests.py
> +                    f"{url}?_changelist_filters=is_staff__exact%3D0",
We should check that currently persisted options work together with other query strings, so I'd add `username=newuser` to new tests:
```suggestion
                    f"{url}?username=newuser&_changelist_filters=is_staff__exact%3D0",
```

2023-10-11 09:02 UTC, felixxm approved these changes
@marianaasilva Thanks :+1: 

I squashed commits, and simplified tests.

2023-10-11 10:45 UTC, merged