add note to staticfiles-ref to address #34813
django/django pull request #17227
Opened 2023-09-04 18:33 UTC by prauscher

After insourcing external references (jquery / bootstrap in this case), I forgot to remove the integrity-attributes and by using ManifestStaticFilesStorage the integrity got broken, the browsers got upset and rendering was broken. When googleing for the errors I received, I could not find a direct match in the reference, hence the ticket #34813 and this pull request.

2023-09-05 12:50 UTC, nessita requested changes

2023-09-05 12:50 UTC, nessita commented on docs/ref/contrib/staticfiles.txt
> +    changes are made, e.g. after they have been collected by ``collectstatic``.
I would re-work this paragraph to make it more explicit about the intent of the admonition, specifically I think the message has to be explicit about how the integrity usage is optional and is separated from the hashes the storage calculates:

```
    If the optional ``integrity`` attribute of the ``<script>`` tag is used,
    the value of its checksum  should be calculated after the resources have
    been collected by ``collectstatic``.
```

2023-09-07 22:44 UTC, prauscher commented
> It seems that this attribute makes sense when you are serving resources hosted on third-party servers, which IIUC is not your case? From your description, I understood you are [vendoring](https://stackoverflow.com/questions/26217488/what-is-vendoring) jquery/bootstrap and serving them from your own server?

That is perfectly correct, however as I was insourcing the files which were hosted on third-party servers before, so the `integrity` attribute was already provided and as I was just vendoring these files I did not realize that Django may change the file while hosting it as static content.

2023-09-07 22:56 UTC, prauscher commented
I did some rework on the admonition, especially to mention different behavior of `ManifestStaticFilesStorage` in `DEBUG` and production-mode. Maybe one should even suggest to not use `integrity` for own static files, but beforehand one would probably need some more research in edgecases like hosting of static files on non-secured storage (not sure if this is a thing, but with an `integrity`-attribute it would at least be not too insecure).

2023-09-07 23:08 UTC, prauscher commented on docs/ref/contrib/staticfiles.txt
> +.. admonition:: Calculation of integrity
That looks way nicer, thanks!

2023-10-31 17:03 UTC, nessita commented
Made further tweakings and rebased onto main.

Current version adds an admonition as follows:
![image](https://github.com/django/django/assets/124304/37e0603a-55f6-4162-902e-c827c8c6ef1b)

2023-10-31 17:20 UTC, nessita approved these changes

2023-11-02 11:25 UTC, merged