Add a mention to ~ (NOT) operator for Q() objects
django/django pull request #17600
Opened 2023-12-12 09:41 UTC by mokazemi

It would be much better to mention `~` `(NOT)` operator in `Q()` object references, too. Though it's said "such as" but including NOT is needed.

2023-12-12 10:31 UTC, shangxiao requested changes
Thanks for the suggestion 🏆 

It's probably not a bad idea to mention here, even though it is documented in the linked section. However technically it's wrong to include it in that sentence about combining Q objects because `~` is specifically a unary operator.

Also the line length of 79 needs to be respected.

2023-12-12 11:00 UTC, felixxm commented on docs/ref/models/querysets.txt
> +combine them using operators such as ``|`` (``OR``), ``&`` (``AND``), ``~`` (``NOT``), and ``^``
`~` is not for combining `Q` objects so it doesn't fit here.

2023-12-12 13:06 UTC, nessita commented
I agree with @felixxm, the `~` can not be used to combine many `Q`s (it's a modifier to a single `Q`).

2023-12-12 14:03 UTC, shangxiao commented
@felixxm @nessita I think what they were trying to get at is that it's worth mentioning `~` in this paragraph as a quick reference. You have to dig into the linked topic to see that it's possible - it's not mentioned until the 7th paragraph.

I was thinking a separate sentence such as "Additionally Q objects can be negated with `~`."

2024-04-12 17:52 UTC, nessita commented
Following up on this, thanks @shangxiao for your comment. I also ask @sarahboyce for her opinion and we agree we can add some clarification. I'll re-open and push small edits and merge.

2024-04-15 16:16 UTC, merged