Refs #30686 -- Fixed text truncation for negative or zero lengths.
django/django pull request #17832
Opened 2024-02-06 19:59 UTC by felixxm

2024-02-06 22:13 UTC, adamchainz requested changes
Add negative tests for completeness?

2024-02-06 22:13 UTC, adamchainz commented on tests/utils_tests/test_text.py
> +        )
```suggestion
        self.assertEqual(
            "",
            truncator.chars(0, html=True),
        )
        self.assertEqual(
            "",
            truncator.chars(-1, html=True),
        )
```

2024-02-06 22:13 UTC, adamchainz commented on tests/utils_tests/test_text.py
> +        self.assertEqual("", truncator.words(0))
```suggestion
        self.assertEqual("", truncator.words(0))
        self.assertEqual("", truncator.words(-1))
```

2024-02-07 04:19 UTC, felixxm commented
> Add negative tests for completeness?

Added.

2024-02-07 07:11 UTC, merged