Removed changing the port in the first part of the tutorial.
django/django pull request #18232
Opened 2024-06-08 09:35 UTC by avallbona

Removing the "Changing port section on the first part of the turorial".
This work is part of effort done in the Sprints in DjangoCon Europe in Vigo with Daniele Procida.

2024-06-08 09:44 UTC, evildmp commented
Agreed that the vast majority of users following the tutorial will a) have no need to do anything about the port and b) will be distracted by this lengthy digression.

2024-06-08 10:14 UTC, evildmp requested changes

2024-06-08 10:41 UTC, avallbona commented on docs/intro/tutorial01.txt
> +reference.
@evildmp Addressed in 9be6c5c1bdb15d19ddc5e0df1cc76c466ec6a24e

2024-06-08 10:42 UTC, evildmp approved these changes

2024-06-08 12:28 UTC, evildmp approved these changes

2024-06-09 07:41 UTC, nessita approved these changes
Thank you, this looks great! :star:

2024-06-09 07:42 UTC, merged