Fixed #35518 -- Used simpler string operations for converter-less routes
django/django pull request #18270
Opened 2024-06-12 19:21 UTC by RealOrangeOne

# Trac ticket number

ticket-35518

# Branch description

The `RoutePattern` assumes all routes provided include some form of converter, and so needs to change it into a regex for matching. However, if no converters are included in the string, the additional overhead of using a regex vs simpler string operations is unnecessary.

Replacing this with a simpler string comparison results in between a 50 and 75% reduction in match time, which stacks up quickly as an application generally has numerous URLs, because `RoutePattern.match` is called once per defined route per request.

**Before**

```python
In [2]: endpoint_pattern = RoutePattern("foo/", "name", is_endpoint=True)

In [3]: pattern = RoutePattern("foo/", "name", is_endpoint=False)

In [4]: %timeit pattern.match("foo/")
441 ns ± 2.68 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [5]: %timeit endpoint_pattern.match("foo/")
435 ns ± 0.974 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

**After**

```python
In [4]: %timeit pattern.match("foo/")
187 ns ± 1.84 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [5]: %timeit endpoint_pattern.match("foo/")
103 ns ± 0.192 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```

(Benchmarked on Python 3.12, running `main`)

Theoretically, these improvements get better based on the length of the route pattern (although at this scale, not notably).

This optimisation could be done by adding a different kind of pattern (eg `LiteralPattern`), but the added complexity to a project probably isn't necessary, not to mention the migration effort to take advantage of this.

# Checklist
- [x] This PR targets the `main` branch. 
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [x] I have checked the "Has patch" ticket flag in the Trac system.
- [ ] I have added or updated relevant tests.
- [ ] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

2024-06-12 20:50 UTC, adamchainz requested changes

2024-06-12 20:50 UTC, adamchainz commented on django/urls/resolvers.py
> +        self._route = str(route)
I think this is not safe for translations. The descriptor at `self.regex` goes through translations. Also, we would still want to apply translations in the new fast path. The cast to string can be done there.

2024-06-12 20:50 UTC, adamchainz commented on django/urls/resolvers.py
> +        self._has_converters = bool(self.converters)
no need, `if self.converters` should be just as fast

2025-01-10 21:37 UTC, pauloxnet approved these changes
LGTM

I added code suggestions to compact a bit the code.

2025-01-10 21:37 UTC, pauloxnet commented on django/urls/resolvers.py
> +
```suggestion
        # If there are no converters, skip the regex overhead and use string operations
        # If this is an endpoint, the path should be exactly the same as the route
        elif self._is_endpoint:
            if self._route == path:
                return "", (), {}
        # If this isn't an endpoint, the path should start with the route
        elif path.startswith(self._route):
            return path.removeprefix(self._route), (), {}
```

2025-01-10 21:37 UTC, pauloxnet commented on tests/urlpatterns/test_resolvers.py
> +
```suggestion
```

2025-05-01 22:04 UTC, RealOrangeOne commented on django/urls/resolvers.py
> +
I disagree - the extra newlines break up each condition, and make it clearer what the comment is for.

2025-05-02 08:05 UTC, RealOrangeOne commented
I've added some more benchmarks to [the ticket](https://code.djangoproject.com/ticket/35518#comment:8) which make the gain clearer.

2025-05-08 16:12 UTC, adamchainz approved these changes

2025-05-13 09:03 UTC, sarahboyce approved these changes
Thank you!

2025-05-13 11:05 UTC, merged