Refs #18296 -- Create custom target directory if missing in startproject and startapp
django/django pull request #18387
Opened 2024-07-18 13:17 UTC by browniebroke

# Trac ticket number

ticket-18296

# Branch description

Given the following project structure, where `apps` is a directory:

```
.
├── apps
├── manage.py
└── myproject
    ├── __init__.py
    ├── asgi.py
    ├── settings.py
    ├── urls.py
    └── wsgi.py
```

If I run:

```bash
$ django-admin startapp app1 apps/app1
CommandError: Destination directory '/Users/bruno/.../myproj/apps/app1' does not exist, please create it first.
```

This is causing some friction, and it feels like it would be something that Django could create out of the box. The code is shared with `startproject`, so this PR is doing it for both, as I couldn't find a reason why it wouldn't apply there too.

# Checklist
- [ ] This PR targets the `main` branch. 
- [ ] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [ ] I have checked the "Has patch" ticket flag in the Trac system.
- [ ] I have added or updated relevant tests.
- [ ] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

2024-07-18 13:51 UTC, browniebroke commented
I _think_ the failing jobs are failing to start due to some infra issues: `java.io.IOException: No space left on device`

Going to assume they're unrelated, but let me know if I miss anything

2025-02-02 16:25 UTC, ryancheley commented on docs/ref/django-admin.txt
>  For example:
Can we call out in the example what this new feature is doing? Something like

For example:

    django-admin startapp myapp /Users/jezdez/Code/myapp/newdirectory

Will create a new directory called `newdirectory` where the app will have its code placed.

2025-02-02 17:01 UTC, ryancheley commented
@browniebroke this looks great. I added a few comments but overall 💯

2025-02-18 18:09 UTC, browniebroke commented on docs/ref/django-admin.txt
>  For example:
I'm not sure this is a good example... The example shopws the `startproject` command, and as written currently, it implies that the project is being created at `/Users/jezdez/Code/myproject_repo`. 

I could however add a line below the command:

> It will create the directory `myproject_repo` if needed, where the project will have its code placed.

What do you think?

2025-02-25 10:43 UTC, sarahboyce reviewed
Thank you! I have initial comments

Note that we need `.. versionchanged:: 6.0` notes for both startapp and startproject.
Also the tutorial currently asks the user to create the directory for the project. We may want to think about updating that

2025-02-25 10:43 UTC, sarahboyce commented on tests/admin_scripts/tests.py
> +    def test_custom_app_destination_missing(self):
Please add more complex examples, such as nested directories which do not exist

2025-02-25 10:43 UTC, sarahboyce commented on django/core/management/templates.py
> +                    raise CommandError(e)
The error handling is missing a test

2025-02-25 14:30 UTC, browniebroke commented
> Also the tutorial currently asks the user to create the directory for the project. We may want to think about updating that

I've updated it, but now that I think about it, I'm wondering whether **now** is the right time to do so... If/when this is merged, the tutorial will be published at the `dev` version (e.g. https://docs.djangoproject.com/en/dev/intro/tutorial01/#creating-a-project) and I assume that some folks might land on this page before v6.0 is released, and would miss the "create directory" step.

Leaving this step in the tutorial still works in v6.0, but removing it would add friction for earlier versions.

2025-03-02 12:16 UTC, browniebroke commented on django/core/management/templates.py
> +                    raise CommandError(e)
> Should I mock `os.makedirs` to raise a specific error to make the test more deterministic?

I've gave this a try

2025-03-02 20:04 UTC, browniebroke commented on django/core/management/templates.py
> +                    raise CommandError(e)
Well, that didn't work because the `self.run_django_admin` helper runs the command in a subprocess. As far as I undertsnad, the mock is applied in the current process, so doesn't trigger. I've tried another approach: by setting the parent directory to be read-only.

2025-03-23 17:55 UTC, LilyFoote approved these changes

2025-04-26 13:29 UTC, g-nie commented on django/core/management/templates.py
> +                    os.makedirs(top_dir)
I wonder if it makes sense to rename the `top_dir` variable to something more generic, since we support nested subdirectories now.

2025-04-26 13:35 UTC, Hikari commented
@browniebroke I checked the docs, ran the tests and tested it. It looks good to me.

2025-04-26 14:11 UTC, TomHall2020 requested changes
Reviewing this:
### Documentation
- [x] Docs build, read ok, changes are reported in the tutorial and cli reference.
- [x] A search on the docs for `django-admin startproject` didn't come up with anything else that needs adjusting in my opinion.
- [x] Release note is included
- [x] I think it might be helpful to include something in the help text on the cli command itself to signal that it can create a missing destination, currently it has no changes and reads as follows:
```
positional arguments:
  name                  Name of the application or project.
  directory             Optional destination directory 
...
```

### Tests
- [x] Test suite is passing
- [x] New tests are written and look suitable.

### Code changes
- [x] Looks good, fairly small changes.

### PR
- [ ] Needs to be [one squashed commit](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#contribution-checklist)

2025-04-26 14:35 UTC, browniebroke commented on django/core/management/templates.py
> +                    os.makedirs(top_dir)
Humm, sure, I don't really mind... The command line argument is called `target`, so guess it could build on that:`target_dir` or maybe `target_path`? What do you think?

2025-04-26 14:36 UTC, browniebroke commented
> * I think it might be helpful to include something in the help text on the cli command itself to signal that it can create a missing destination

Great idea, added. Thanks!

2025-04-26 14:39 UTC, g-nie commented on django/core/management/templates.py
> +                    os.makedirs(top_dir)
Either sounds good to me, thanks!

2025-04-26 15:40 UTC, TomHall2020 commented
All good for me now 👍

2025-04-26 16:02 UTC, TomHall2020 approved these changes

2025-04-26 16:09 UTC, g-nie approved these changes

2025-04-26 16:18 UTC, browniebroke commented
Rebased and squashed all the commits into one as per contribution guidelines

2025-04-27 10:07 UTC, sarahboyce reviewed
Thank you @browniebroke and everyone for all the reviews :star: 

I was going through and when testing locally I tried to create an app within an app, this raised an error:
```
(test-django-package) sarahboyce@sarahboyce-ThinkPad-E15-Gen-4:~/Documents/Django-notes/Projects/test-django-package/mysite$ python manage.py startapp app75 app7/app75
Traceback (most recent call last):
  File "/home/sarahboyce/Documents/Django-notes/Projects/test-django-package/mysite/manage.py", line 22, in <module>
    main()
  File "/home/sarahboyce/Documents/Django-notes/Projects/test-django-package/mysite/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/sarahboyce/.pyenv/versions/test-django-package/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/sarahboyce/.pyenv/versions/test-django-package/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sarahboyce/.pyenv/versions/test-django-package/lib/python3.12/site-packages/django/core/management/base.py", line 416, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sarahboyce/.pyenv/versions/test-django-package/lib/python3.12/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sarahboyce/.pyenv/versions/test-django-package/lib/python3.12/site-packages/django/core/management/commands/startapp.py", line 14, in handle
    super().handle("app", app_name, target, **options)
  File "/home/sarahboyce/.pyenv/versions/test-django-package/lib/python3.12/site-packages/django/core/management/templates.py", line 207, in handle
    with open(new_path, "w", encoding="utf-8") as new_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/sarahboyce/Documents/Django-notes/Projects/test-django-package/mysite/app7/app75/migrations/migrations/__init__.py'
```
Can you take a look?

2025-04-27 11:23 UTC, browniebroke commented
Nice catch. Quick question: did you rebase from main or did you only split the commit into 2? I'm pretty confident CI was green last night but it's now broken. I _think_ the split when wrong because the variable was renamed from `top_dir` -> `target_path` and then changed to `target_dir`, but `target_dir` is already used in `main` further down in the file:

https://github.com/django/django/blob/fbdbccf27a7d969a92e6ab8d2b7754e21e69b050/django/core/management/templates.py#L164

That might explain why we're getting `migrations` twice in the path `test-django-package/mysite/app7/app75/migrations/migrations/__init__.py`, as we're joining from the wrong base path? 

In the interest of keeping this PR focused, I'm tempted to keep the `top_dir` name? Open to suggestions for better names :)

2025-04-27 11:55 UTC, browniebroke commented
> I was going through and when testing locally I tried to create an app within an app

I've added a test to cover this specific case `test_custom_name_with_app_within_other_app` - let me know if you're happy with the approach or if you have any suggestions. Thanks!

2025-04-27 13:03 UTC, sarahboyce approved these changes
Thank you! :star:

2025-04-27 13:41 UTC, merged