Ticket 35813 - Add AlterField functionality to makemigrations for unmanaged models
django/django pull request #18651
Opened 2024-10-04 22:54 UTC by hannylicious

#### Trac ticket number

ticket-35813

#### Branch description
Unmanaged models had no history of alterations being done to them. This PR fixes that issue so that any changes made to unmanaged models will be reflect in the same fashion as managed models (which is indicated as the expected behavior per the docs)

#### Checklist
- [ x ] This PR targets the `main` branch. 
- [ x ] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [ x ] I have checked the "Has patch" ticket flag in the Trac system.
- [ x ] I have added or updated relevant tests.
- [ x ] I have added or updated relevant docs, including release notes if applicable.
- [ x ] I have attached screenshots in both light and dark modes for any UI changes.

2024-10-05 03:40 UTC, charettes reviewed
Hello @hannylicious!

The patch seems to be on the right way but I suspect that more fundamental changes will be required to have the auto-detector keep track of all model changes.

If we are going to make this change it should not only detect field changes on unmanaged models for all kind of changes (model/field renames, constraint/index additions/alterations).

I suspect the approach we'll want to have here is to stop partitioning model keys by managed or not by getting of `kept_unmanaged_keys` and `old_unmanaged_keys`.

2024-10-05 03:48 UTC, charettes commented
From some local test removing all the unmanaged model specialization from the autodetector passes the full suite and the test you added so that seems to support the idea that it's an avenue worth exploring.

2024-10-05 12:18 UTC, hannylicious commented
> Hello @hannylicious!
> 
> The patch seems to be on the right way but I suspect that more fundamental changes will be required to have the auto-detector keep track of all model changes.
> 
> If we are going to make this change it should not only detect field changes on unmanaged models for all kind of changes (model/field renames, constraint/index additions/alterations).
> 
> I suspect the approach we'll want to have here is to stop partitioning model keys by managed or not by getting of `kept_unmanaged_keys` and `old_unmanaged_keys`.

I agree. However there were a couple test that began to break when I applied that methodology, so I decided to rework things and go with this approach. I'll take another crack at it!

2024-10-07 18:01 UTC, hannylicious commented
@charettes - in reviewing your changes compared to what I had originally, I think the reason I saw test failures was that I had not fully implemented the changes in all appropriate places in the file. Thanks for your local diff - I've went ahead and went forward using that as a guide, updated the PR and added a number of additional tests for various scenarios to ensure things are getting treated appropriately. 

I imagine there are probably a lot more edge cases that could potentially be added to the test suite, but I think the tests added help to cover a lot of the main use cases and further ensure both unmanaged/managed migrations get treated equally in order to comply with the ideas Django has set forth in the docs.

I do wonder if having an option to 'not include unmanaged models in migrations' would be of benefit (I think it would be); but that's a discussion for a different PR all together.

2024-10-07 18:12 UTC, charettes commented
Thanks for the adjustments and the additional tests ⭐ 

> I do wonder if having an option to 'not include unmanaged models in migrations' would be of benefit (I think it would be); but that's a discussion for a different PR all together.

I also think this should be brought up as a distinct issue on the form, I do fear complications around what happens if you stop passing the option mid-project. I think that concurrent work such as #18445 (ticket-35656) could address your issue though as you would _only_ have to define your own `autodetector_class` that purge unmanaged model entries from `new_model_keys`.

2025-04-26 13:11 UTC, kevingill1966 commented
I reviewed this ticket.

I followed the checklist as per: https://docs.djangoproject.com/en/dev/internals/contributing/new-contributors/#guidelines

1. The patch fixes the problem.
2. The tests fail without the patch, and succeed with the patch.
3. The patch passes the checkers black, sort, flake8, and blacken-doc

### Packaging Issues

1. The PR does not provide a single commit. There are two commits. The commit message does not follow the guidelines as per:  https://docs.djangoproject.com/en/dev/internals/contributing/committing-code/#committing-guidelines

2. The PR is not documented in the release documentation.

### Conclusion

This PR works well. The patch should be merged. It just needs to be prepared for the merge process.

2025-05-08 14:40 UTC, hannylicious commented
@kevingill1966 I believe I have updated everything with the changes you requested. Let me know if you see any other things that might need changing!

2025-07-16 13:26 UTC, nessita commented
> @kevingill1966 I believe I have updated everything with the changes you requested. Let me know if you see any other things that might need changing!

Hello @hannylicious! Thank you for your work in this PR.

If you haven't already, please read the [Contribution checklist](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/submitting-patches/#patch-review-checklist) to ensure that the proper flags are updated in the Django Trac sytem to have this listed in the [pending review queue](https://code.djangoproject.com/query?status=!closed&needs_better_patch=0&needs_tests=0&needs_docs=0&has_patch=1&stage=Accepted&desc=1&order=changetime).

2025-07-17 15:38 UTC, hannylicious commented
@nessita thanks for the heads up! I didn't realize I needed to update the ticket. I have done so, as well as updated the pr to reflect the most recent django code.

2025-07-17 15:49 UTC, nessita commented
> @nessita thanks for the heads up! I didn't realize I needed to update the ticket. I have done so, as well as updated the pr to reflect the most recent django code.

Thank you for doing that! A minor clarification: a PR author should never mark their own ticket as "Ready for checkin", only reviewers would do that once the work is actually ready to be merged.

2026-01-30 11:49 UTC, blighj requested changes
Thanks again for doing this, shame it fell by the wayside. I've retested it against the latest master and the issue is still there and this patch still fixes it.

To move it forward the PR needs to be rebased and as I suggest the release docs now need to be updated.. Once that is done, we can update the trac ticket so "Needs Documentation" is unset and it will be back in the review queue and maybe it will have a chance of a review for 6.1 or 6.2.

2026-01-30 11:49 UTC, blighj commented on docs/releases/5.2.5.txt
> +  unmanaged models in the same way as managed models (:ticket:`35813`).
As per @charettes suggestion about noting that `it might cause new changes to be detected on upgrade.` for unmanaged models. Something like the below could cover it.

```suggestion

* The :djadmin:`makemigrations` command now properly tracks all changes to
    unmanaged models, including field additions, removals, alterations,
    constraints, and model renames. After upgrading, you may see new
    migrations detected for unmanaged models that have pending changes
    (:ticket:`35813`).
```
This also needs to be moved to a new releases file, I'd suggest `docs/releases/6.1.txt`. i'd take the length of time it has taken to get reviewed and merged as a sign that it is not really a bug fix release issue.

2026-03-10 19:29 UTC, hannylicious commented on docs/releases/5.2.5.txt
> +  unmanaged models in the same way as managed models (:ticket:`35813`).
I'm going to update this per your suggestions (it does seem more accurate). However, I am going to update it in a bugfix as that still seems to be what this is. I take the length of time this has taken to get reviewed and merged, simply as a sign that this particular bug is unimportant to most (but is important for me, personally as I deal with a _lot_ of unmanaged models).

2026-03-10 20:27 UTC, hannylicious commented
@blighj Everything updated and passing, do I need to go remove the needs documentation check on the ticket now to get this some attention?

2026-03-10 20:36 UTC, blighj commented
I've updated that earlier, so this ticket is in the queue again, but it's a very busy at the minute, there are almost a 100 tickets in the queue, normally it is a third of that. It's shot up in the last week or two.

2026-03-25 13:06 UTC, hannylicious commented
@blighj Being newer to this - and having this as my first PR - what is the general timeline for something like this? Given that it's been commented on by @charettes and others and has been open for well over a year, is there any way to get this some attraction and attention to be accepted?

As I said, this is kind of an important one because we use a lot of unmanaged models. Just wondering if priority in the queue is determined by time frame or something else. I would think almost 1.5 years for a PR is a pretty exhaustive timeline and waiting that amount is more than patient.

2026-03-25 13:59 UTC, blighj commented
There is a bit of a perfect storm hitting django/open source this March. AI and google summer of code.

Django is volunteer lead, there is no big tech firm behind it, some volunteers do fund raising which pays for some promotion/education and for 2 fellows who help keep tickets and PR's moving as well as making sure security always gets the attention in needs. nessita is one of those fellows. After that PR's move from volunteers like charettes, who give their time to review PR's. I would only class myself as a longtime django user, not a contributor.

AI has had two big impacts in the last 12 months, the biggest one seems to be security reports.
Django prioritises security, which is one of the main reasons I've been a user. If someone finds a security problem with django they are encouraged to submit a report and it is handled privately and mainly by the fellows.
There are different motivations for these reports from wanting to fix an issue that affects their business, wanting to make the internet safer, wanting to demonstrate competence to employers/courses, to wanting to make a claim against third party bug bounty programs.
Pre AI the number of people with the technical expertise to find and submit the reports was small, so the effort on behalf of the fellows was fine. With AI the effort to create a report is much smaller and by all accounts incoming reports have being growing to the point that it now takes up most of the fellows time.

The google summer of code problem is a similar story, it is a great program where google sponsor students to work on open source. Django has had some great contributions from this program over the last few years. The deadline for proposals is March 31st. Free money and good experience is competitive so to help stand out, google's docs suggest getting some PR's merged in your target project first, which is good advice, and normally a bit of a sorting function. But again with AI it is no longer such a daunting task and the number of PR's in the last month has been unusually high. I'm not even saying they are slop, but they are definitely more.

So instead of a ticket like this been one of 20-30, it's in a list of a 100+, and the team are still moving quite a few each week, I count 18 commits last week, which I find amazing given the security report issue. It was the size of the queue that motivated me to go look for tickets like this that were solid contributions that might need a little bump back to the top. But even with the bump I'd have low expectations for the next while. Django releases version 6.1 in August, so they have a sensible approach of freezing what will be released in mid May, about 6 weeks time. I don't have any real insight into how to get ticket seen by then. Assuming it's not then you are looking at 6.2, which is another year away!  A competent reviewer like charettes approving this PR and moving it the ticket to ready for checking would move it along. Me doing those steps would do nothing as I don't have the skills/respect to know the true value. It does seem valuable to me but you know the dunning kruger effect right?

I don't really understand charettes point about
>I think that concurrent work such as https://github.com/django/django/pull/18445 ([ticket-35656](https://code.djangoproject.com/ticket/35656)) could address your issue though as you would only have to define your own autodetector_class that purge unmanaged model entries from to_state before proceeding with changes detection.

Does the work done there give you a different work around or a way to simplify this PR perhaps? Or is it only relevant to the discussion on the option to 'not include unmanaged models in migrations'?

In the meantime, the changes are relatively small right, you're probably doing this already, but I'll say it just in case, you can patch your version of django with your changes or pip install django from your own repo, or a bunch of other technical ways I've used in the past to have code I'd like in django to at least be usable on my own projects.

That was longer than I was expecting, but I'm probably convincing myself of the need to be patient as much as you. I'm convinced anyway.

2026-03-25 14:49 UTC, hannylicious commented
Thank you @blighj for that in depth discussion. I appreciate it. 

I really dislike the idea of having to patch locally and all that - I know it can be done, I just really find it a pain. 

I'm both thankful for some of the stuff AI has made easier (e.g. writing boilerplate is easier now!), but it has made a lot of things, a lot of extra work - and not necessarily for the better. Apparently the fallout of this being felt in the Django community is just 'par for the course', which is unfortunate. I guess we just have to adapt.

I can't remember the specifics surrounding the ticket that charettes linked, but I do recall reading through it and continuing on with this. It's been so long now, hard to remember exactly. 

I appreciate the discussion regardless. Thank you.

2026-03-29 20:04 UTC, charettes commented
I don't have much to add to what @blighj said with regards to LLM tax on FOSS.

Security team, which has a large overlap with review and triage team, has been dealing with a large influx of reports that almost look right and require significant time investment to triage and we've been fighting [SPAM quality PR submission from accumulating](https://github.com/django/django/pulls?q=is%3Apr+is%3Aclosed).

We are developing processes to help in the triage efforts but there is only so much time volunteers and fellows can spend in a day fighting it and it unfortunately shift their focus away from other important work.

@blighj 

> I don't really understand charettes point about
>> I think that concurrent work such as https://github.com/django/django/pull/18445 ([ticket-35656](https://code.djangoproject.com/ticket/35656)) could address your issue though as you would only have to define your own autodetector_class that purge unmanaged model entries from to_state before proceeding with changes detection.

In [this comment](https://github.com/django/django/pull/18651#issuecomment-2397579890) I meant that allowing a pluggable auto-detector class as described ticket-35656 (which landed a week after this comment in October 2024) could be a way for folks to opt-out of unmanaged model detection if they wanted to. I suggested opening a forum discussion about it to gather feedback on whether this PR should include a `AutoDetector.track_unmanaged_model: bool` attribute to restore the previous behaviour if needed as I wouldn't be surprised the moment this change lands users might complain that they preferred it the other away around.

Now for the review parts @hannylicious I think that this patch is only missing two things before it's ready for a final look from a fellow

1. Move the release notes to 6.1
2. Change the commit message (that could be done by a merger) to something more factual like `Fixed #35813 -- Made migration auto-detector track all unmanaged model changes`. You could use the body of the commit to describe why this is a good change and what kind of problems it resolves but parts like _as expected_ can be said about any changes resolving problems.

Once this is done I'll be happy to mark the patch as ready for a review by a merger but you'll likely need to wait a bit as their cycles remains quite reduced due to situation described above.

2026-03-29 20:04 UTC, charettes commented on docs/releases/6.0.4.txt
> +* The :djadmin:`makemigrations` command now properly tracks all changes to
We don't document bugfixes but this has turned into new feature to track all managed models. In all cases a mention you be added to 6.1 instead. You should also drop the ticket reference in the 6.1 release note.

Once a version of Django is released it only receives security fixes and patches fixing regressions introduced in the version itself. Since this has been an issue for many releases it's no eligible for a backport.

2026-03-29 20:04 UTC, charettes commented on tests/migrations/test_autodetector.py
> +        """Test change detection of new constraints."""
We usually don't include docstrings that are redundant with the test name as don't provide much value. I see that this test module doesn't necessarily follows this convention though.

2026-03-29 20:04 UTC, charettes commented on docs/releases/5.2.5.txt
> +  unmanaged models in the same way as managed models (:ticket:`35813`).
> I'm going to update this per your suggestions (it does seem more accurate). However, I am going to update it in a bugfix as that still seems to be what this is

We only backport security fixes and [bug fixes for critical problems](https://docs.djangoproject.com/en/6.0/internals/release-process/#supported-versions) which this one doesn't qualify to and is borderline a new feature. You should target the 6.1 release notes as @blighj suggested and avoid referencing the ticket.

> I take the length of time this has taken to get reviewed and merged, simply as a sign that this particular bug is unimportant to most (but is important for me, personally as I deal with a lot of unmanaged models).

I'm sorry this is taking longer than you'd expect but I suspect that the tens of contributors who also have tickets waiting for a review share the same sentiment as you; they are hoping to solve a problem that is important to them first which doesn't necessarily mean it's not an important one to solve.

More on why the review queue has been growing that much but a good way to get folks to review your important changes is to review theirs.

2026-05-22 00:06 UTC, timgraham commented
I'd suggest to update the PR description to "Fixed #35813 -- Made migrations track all changes to unmanaged models." The second line of the commit message could elaborate: "Previously, only create and delete operations were generated." There might be time to get this merged as a bug fix for Django 6.1 before it reaches "beta" status next month. 

(The fix is of interest to me as I'm experimenting with making Django MongoDB Backend's `EmbeddedModel` unmanaged as a way of preventing `SchemaEditor` from operating on it, as well as a way of detecting embedded models in the autodetector. I believe I need `AddField`, `AlterField`, etc. operations for embedded models so that their model state is updated with added/removed/changed fields.)

2026-05-27 15:01 UTC, hannylicious commented
Not sure if it's too late for review into 6.1 - but I've updated this PR in order to better reflect what it does as a feature in 6.1.

I am grateful for the help/guidance offered in this thread! This has been a great way to learn more on helping to make Django better.

2026-05-27 15:32 UTC, blighj approved these changes

2026-06-01 20:17 UTC, timgraham reviewed
The PR title still uses the old commit message.

2026-06-01 20:17 UTC, timgraham commented on django/db/migrations/autodetector.py
"unmanaged" could also be removed from this docstring.

2026-06-01 20:17 UTC, timgraham commented on docs/releases/6.1.txt
> +  models, including field additions, removals, alterations, constraints and
constraints, (add comma)

2026-06-01 20:17 UTC, timgraham commented on docs/releases/6.1.txt
> +  unmanaged models that have changed.
"have changed since their creation."

2026-06-01 20:17 UTC, timgraham commented on tests/migrations/test_autodetector.py
> +        """Test change detection of new constraints."""
I guess all docstrings should have "on an unmanaged model." (only one does)

2026-06-01 20:17 UTC, timgraham commented on tests/migrations/test_autodetector.py
> +        """Tests autodetection of new fields on an unmanaged model."""
new -> altered

2026-06-10 11:35 UTC, hannylicious commented
I've made the requested changes (which were great, thanks Tim!)

2026-07-08 07:44 UTC, sarahboyce reviewed
Hello hello 😁 thank you all for the work on this PR, it looks really good

I am concerned that, due to the changes to unmanaged models not being detected previously, some folks may have been able to change their models in ways that wouldn't normally be allowed. Then when trying to upgrade now, they would struggle

An example upgrade paper cut is adding fields without defaults. Someone upgrading now may be bombarded with a lot of fields they need to provide one off defaults for. Though this isn't an example that I am too worried about

I was specifically concerned about adding and changing `CompositePrimaryKey`s as this is something the docs say we do not support, and is a real example within djangoproject.com, but when testing this wasn't an issue in practice

Are there any examples folks can think of where that could prove to be an issue? Perhaps we would need a section within the release notes that would have space for upgrade guidelines if required. We may need to clearly explain the value as I can see folks being like "this has been work for me and I don't see the value".

2026-07-09 13:34 UTC, sarahboyce approved these changes
I don't think my concern was well founded 😁 
Thank you all

2026-07-10 09:58 UTC, merged

2026-07-17 20:29 UTC, jacobtylerwalls commented
Thanks everyone for seeing this through!

> I don't think my concern was well founded 😁

Not giving yourself enough credit there! I do wonder if we should consider a solution for:

> An example upgrade paper cut is adding fields without defaults. Someone upgrading now may be bombarded with a lot of fields they need to provide one off defaults for. 

I just experienced that in a test project. Do we want the autodetector to complain in this situation? On first impression, if a model is _unmanaged_, then it isn't really "impossible" to add a non-nullable default for a field. Someone else is managing that table.

What do folks think?

2026-07-21 17:23 UTC, jacobtylerwalls commented
Opened ticket-37224 to discuss this ☝️

2026-07-21 17:31 UTC, hannylicious commented
Great ticket to open @jacobtylerwalls and thank you @sarahboyce for initially pointing out those 'sharp edges' that come with this change. I think your initial thoughts have merit and are important considerations! 

I think the autodetector probably shouldn't complain, because if it's an unmanaged model, while we want to see changes, I don't think we want it asking us for default information. It's unmanaged for a reason, so I think it's safe to assume we want it to not complain, just accept what we tell it as true.