Fixed #17461 -- Doc'd the presumed order of foreign keys on intermediary M2M model.
django/django pull request #18762
Opened 2024-11-04 08:47 UTC by cliff688

#### Trac ticket number

ticket-17461

#### Branch description
This PR addresses ticket #17461 by updating the documentation to clarify the order of foreign keys when defining an asymmetric many-to-many relationship that uses an intermediary model.

#### Checklist
- [x] This PR targets the `main` branch. 
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [x] I have checked the "Has patch" ticket flag in the Trac system.
- [ ] I have added or updated relevant tests.
- [x] I have added or updated relevant docs, including release notes if applicable.
- [ ] I have attached screenshots in both light and dark modes for any UI changes.

2025-04-26 12:58 UTC, g-nie requested changes
Hey @cliff688 👋
I left some minor suggestions

2025-04-26 12:58 UTC, g-nie commented on docs/topics/db/models.txt
> +  must specify ``through_fields``, or a validation error will occur.
I would leave the last sentence (almost) as is:
```
If  there are *more* than two foreign keys, you must also specify ``through_fields`` as above, or a validation error will be raised.
```

2025-04-26 12:58 UTC, g-nie commented on docs/ref/models/fields.txt
> +        foreign key must come before the ``clients`` foreign key in the
I think this should be **`client`** here, so:

`... foreign key must come before the ``client`` ...`

2025-04-26 13:25 UTC, cliff688 commented on docs/topics/db/models.txt
> +  must specify ``through_fields``, or a validation error will occur.
Thanks for the review @g-nie! I notice I also changed the first sentence needlessly, I will revert that as well

2025-04-26 13:26 UTC, cliff688 commented on docs/ref/models/fields.txt
> +        foreign key must come before the ``clients`` foreign key in the
Good catch!

2025-04-26 14:40 UTC, g-nie approved these changes

2025-04-30 11:39 UTC, sarahboyce reviewed
Thank you @cliff688 :star: 

This looks good, I have some questions I'd love to hear your opinions on

2025-04-30 11:39 UTC, sarahboyce commented on docs/ref/models/fields.txt
> +                    "self", symmetrical=False, related_name="suppliers"
Does this not need `through="Supply"`?

2025-04-30 11:39 UTC, sarahboyce commented on docs/ref/models/fields.txt
> +        itself using an intermediary model, the first foreign key in the
Should we mention that this is without defining `through_fields`?

2025-04-30 11:39 UTC, sarahboyce commented on docs/topics/db/models.txt
> +  relationship. The first foreign key in the intermediary model will be taken
Also similar question as to whether saying, "If ``through_fields`` is not specified, the first foreign key..."

2025-04-30 13:21 UTC, cliff688 commented on docs/ref/models/fields.txt
> +                    "self", symmetrical=False, related_name="suppliers"
Oops 😅

2025-04-30 13:22 UTC, cliff688 commented on docs/ref/models/fields.txt
> +        itself using an intermediary model, the first foreign key in the
Yes, thanks for pointing that out 👍🏾  I tested it out and if `through_fields` is specified in the correct order then the order of fk definitions in the intermediary model is irrelevant.

2025-04-30 14:47 UTC, sarahboyce approved these changes
Thank you! I pushed minor tweaks :+1:

2025-05-02 06:56 UTC, merged