Fixed #35908 - Retired django-developers and django-users mailing list.
django/django pull request #18808
Opened 2024-11-14 03:28 UTC by chaitanyarahalkar

#### Trac ticket number
ticket-[35908](https://code.djangoproject.com/ticket/35908)

#### Branch description

Retired django-developers and django-users mailing list. 

Completed the following 
- [x] Remove 2x mailing lists from the [​How to release Django](https://github.com/django/django/blob/main/docs/internals/howto-release-django.txt#L132) docs
- [x] Remove django-users from the [​FAQ - How do I do X](https://github.com/django/django/blob/main/docs/faq/help.txt#L24)
- [x] Remove [​Why hasn't my message appeared on *django-users*?](https://github.com/django/django/blob/main/docs/faq/help.txt#L44) from the FAQ: Getting help
- [x] Remove [​You might notice we have a second mailing list](https://github.com/django/django/blob/main/docs/faq/help.txt#L71) paragraph from the FAQ: Getting help
- [x] Remove the 4x subscription and posting email addresses from [​Mailing lists and Forum](https://github.com/django/django/blob/main/docs/internals/mailing-lists.txt#L33)
- [x] Remove the django-users mention on the [​Contributing to Django](https://github.com/django/django/blob/main/docs/internals/contributing/index.txt#L29) index.
- [x] Remove 4x mentions of django-developers from the [​Organization of the Django Project](https://github.com/django/django/blob/main/docs/internals/organization.txt#L218) docs
- [x] Remove 3x django-developers mentions on [​Comitting code](https://github.com/django/django/blob/main/docs/internals/contributing/committing-code.txt#L113)
- [x] Remove 6x django-developers mentions on [​Triaging tickets](https://github.com/django/django/blob/main/docs/internals/contributing/triaging-tickets.txt#L312)
- [x] Remove 4x django-developers mentions on [​Submitting contributions](https://github.com/django/django/blob/main/docs/internals/contributing/writing-code/submitting-patches.txt#L157)
- [x] Remove 1x django-developers mention from [​Writing your first contribution for Django](https://github.com/django/django/blob/main/docs/intro/contributing.txt#L44)

Rewrite tasks
- [x] Rewrite the [​Mailing lists and Forum](https://github.com/django/django/blob/main/docs/internals/mailing-lists.txt#L33) explanations for django-users and django-developers to explain the mailing lists still exist and contain valuable history
- [x] Replace the 4x django-users and django-developers mentions on [​Reporting bugs and requesting features](https://github.com/django/django/blob/main/docs/internals/contributing/bugs-and-features.txt#L20) to instead point to the forum
- [x] Replace the django-users and IRC links on the [​What to read next](https://github.com/django/django/blob/main/docs/intro/whatsnext.txt#L126) with a link to the [​Django Community](https://www.djangoproject.com/community/) page
- [x] Replace the django-users mention on [​contrib apps index](https://github.com/django/django/blob/main/docs/ref/contrib/index.txt#L141) with a link to the Django forum

#### Checklist
- [x] This PR targets the `main` branch. 
- [x] The commit message is written in past tense, mentions the ticket number, and ends with a period.
- [x] I have checked the "Has patch" ticket flag in the Trac system.
- [x] I have added or updated relevant tests.
- [x] I have added or updated relevant docs, including release notes if applicable.
- [x] I have attached screenshots in both light and dark modes for any UI changes.

2024-11-14 09:05 UTC, sarahboyce reviewed
Thank you for starting this @chaitanyarahalkar

There are still references to `|django-developers|` and `|django-users|` which I would expect to be removed in:
- `docs/misc/distributors.txt`
- `docs/internals/contributing/bugs-and-features.txt`
- `docs/internals/howto-release-django.txt`

In `docs/internals/mailing-lists.txt` there is docs on the user and developer mailing lists, I think these should be moved to the bottom and updated to be "past tense" and very clear that these should be treated as read-only 

I also think as part of this change the `rst_epilog` should be updated to have shortcut links to the form (and possibly the Discord)

2024-11-14 11:07 UTC, sarahboyce commented
> I also think as part of this change the `rst_epilog` should be updated to have shortcut links to the form (and possibly the Discord)

I will work on this here: https://github.com/django/django/pull/18809 so don't worry about this bit

2024-11-14 13:17 UTC, thibaudcolas requested changes
Thank you for giving this a go @chaitanyarahalkar! I’ve not reviewed files that weren’t changed like Sarah has but here are a few other points.

2024-11-14 13:17 UTC, thibaudcolas commented on docs/internals/contributing/writing-code/submitting-patches.txt
>  --------------------------------------------------
This will need adjusting to match the title length, no?

2024-11-14 13:17 UTC, thibaudcolas commented on docs/internals/howto-release-django.txt
>    * `django-announce <https://groups.google.com/g/django-announce/>`_
Presumably it would be better to rephrase the bullet right above?

2024-11-14 13:17 UTC, thibaudcolas commented on docs/internals/mailing-lists.txt
> -* `django-announce subscription email address`_
Here and django-updates below: this should stay as-is.

2024-11-14 13:17 UTC, thibaudcolas commented on docs/internals/organization.txt
> -    Forum
This should remain, just remove the mailing list reference

2024-11-14 13:17 UTC, thibaudcolas commented on docs/intro/whatsnext.txt
> +particular Django setup, try the Django Community page at https://www.djangoproject.com/community
Here and for `docs/ref/contrib/index.txt`: we should use an actual reStructuredText link, not just the URL within text.

2025-01-22 19:21 UTC, thibaudcolas requested changes
Thank you @chaitanyarahalkar, improvements looking good, there is more to do. I’ve updated my code review to be a bit easier to take over.

2025-01-22 19:21 UTC, thibaudcolas commented on docs/intro/whatsnext.txt
>  .. _#django IRC channel: https://web.libera.chat/#django
```suggestion
particular Django setup, try the `Django Community page`_ instead.

.. _ticket system: https://code.djangoproject.com/
.. _#django IRC channel: https://web.libera.chat/#django
.. _Django Community page: https://www.djangoproject.com/community/
```

2025-01-22 19:21 UTC, thibaudcolas commented on docs/ref/contrib/index.txt
> +Code it up, and post it to the Django forum at https://forum.djangoproject.com.
```suggestion
Code it up, and post it to the `Django Forum`_.

.. _Django Forum: https://forum.djangoproject.com/
```

2025-01-22 19:21 UTC, thibaudcolas commented on docs/internals/organization.txt
> -    Forum
```suggestion
  - Discussions about Django on the Django Forum
```

2025-01-23 05:44 UTC, chaitanyarahalkar commented on docs/intro/whatsnext.txt
>  .. _#django IRC channel: https://web.libera.chat/#django
thanks for taking this @thibaudcolas. Changes look good to me.

2025-02-05 12:18 UTC, sarahboyce commented
Thank you for your work here @chaitanyarahalkar 
I have incorporated your changes and added you as a co-committer in https://github.com/django/django/pull/19141

2025-02-05 12:18 UTC, closed without merging